### ISSUE TITLE
Integrating context menu icons into FF-GX

### ISSUE THREAD

**Issue by silverwings15** [Godiesc/firefox-gx#100]
hi, thank you very much for this amazing theme which i only recently discovered. i'd like to ask if you have any plan of adding context menu icons to the theme? for example, Lepton (https://github.com/black7375/Firefox-UI-Fix/) and duskFox (https://github.com/aminomancer/uc.css.js/) do a great job of this, if you perchance needed some inspiration. i took a shot at doing it myself, but the results are less than satisfactory at best.. 
![image](https://github.com/Godiesc/firefox-gx/assets/10742312/ae708bb5-031d-4d16-b72e-3365dadba521)

would love to hear back from you!

**Comment by Godiesc** [comment]
hi,
there are a lot of contextual menus and seems a lot to do jeje, but maybe I could start with some in a near future.

**Comment by silverwings15** [comment]
that would be awesome indeed!
