### ISSUE TITLE
 problems with tabs

### ISSUE THREAD

**Issue by soilentgreen** [Godiesc/firefox-gx#102]
Hi Godiesc, how are you?

I updated  just now to  librewolf  119.0.1-1, and there is problems on my tabs, hope you can help me with:

1) The background of the chosen tab has red color instead only black. How can I make the background black?
2) The edges of the tab is not right.

I put the latest ogx_tab-shapes.css but no fix.

I didn't updated to your latest version of your theme, because I did so many changes, so I prefer to fix this with the version I use.
Can you tell me please what I should to for fix it? 
Thanks.
![1111111](https://github.com/Godiesc/firefox-gx/assets/7990597/bd857584-3bf9-4f9e-9514-25d71406ab06)

**Comment by soilentgreen** [comment]
I managed ro fix the edges tab, but no the red background

**Comment by Godiesc** [comment]
hi, its hard to help you if the code is old with your edits, you can try with the developer console, I always said for extra code or edits you should use the tricks file.

**Comment by soilentgreen** [comment]
Hi Godiesc, 
Thank you for the replay :)
I replace the old ogx_tabs-bar.css with the one from v.119, and the red background disappeared.
But the thickness is not right. Look the difference between the old and new (v.119) of australis shape.
I tried to change some "pxs" in the code, tried to make the border more thin but no success. 

And another thing do you know how can I bring back the menu with firefox icon at the top left corner? Mine is gone.
![11111](https://github.com/Godiesc/firefox-gx/assets/7990597/33b1b102-197b-4129-961e-6ad1c19fb896)

**Comment by Godiesc** [comment]
be sure the userChrome.css has the entry for ogx_menu.css, and the ogx_menu.css is in components folder.
if you replace the ogx_tab-shapes.css and pgx_tabs-css should be enough to solve that problem, taht is caused for the height of the gradient, try to put 0px to this line: https://github.com/Godiesc/firefox-gx/blob/218514ac43d7ebcc254ba220a023b9d3cd0b586a/chrome/components/ogx_tabs-bar.css#L89

**Comment by soilentgreen** [comment]
> try to put 0px to this line:

This is fix the problem. Thank you very much :-)

Do you know how can I bring back the menu with firefox icon at the top left corner? Mine is gone. And I can't find how to do it.
![11111](https://github.com/Godiesc/firefox-gx/assets/7990597/cf974514-eb2e-4b58-a4e6-04b8fd20ecf4)

**Comment by Godiesc** [comment]
> be sure the userChrome.css has the entry for ogx_menu.css, and the ogx_menu.css is in components folder.

**Comment by soilentgreen** [comment]
yes userChrome.css has the entry for ogx_menu.css, and the ogx_menu.css is in components folder.
maybe something in the settings need to be changed?

**Comment by Godiesc** [comment]
that file is for default in windows and linux, in macOS isn't. Don't need any extra steps.

**Comment by soilentgreen** [comment]
I replaced the userChrome.css and ogx_menu.css with the new one and  it bring back  the icon menu .
now the theme is perfect to me. 
Thanks again for help me :-)
