### ISSUE TITLE
Tab shapes won't change

### ISSUE THREAD

**Issue by GrPK** [Godiesc/firefox-gx#104]
Hello! Using latest v120 (but I had this bug as well in 119). Tab shape won't change and it will only stay on Edge version (I think, it is the closest ressemblance). I'd attached screenshot with all my settings

![image](https://github.com/Godiesc/firefox-gx/assets/31523635/c0a34a29-302f-4e68-a81b-158664e3c34b)
![image](https://github.com/Godiesc/firefox-gx/assets/31523635/c61f5e79-6ce8-46a5-88d6-5eee1800ea3a)

![image](https://github.com/Godiesc/firefox-gx/assets/31523635/86ded428-2002-4cff-8305-a1d084b3cbeb)
![image](https://github.com/Godiesc/firefox-gx/assets/31523635/d03339e5-bffd-468f-a715-65669e6dbb38)
![image](https://github.com/Godiesc/firefox-gx/assets/31523635/3f9c8c87-b1d3-4384-979e-80c2d5cafc88)

Did I do something wrong?

**Comment by Godiesc** [comment]
I tested it and seems all right.


https://github.com/Godiesc/firefox-gx/assets/22057609/e9ed8fd2-7b7f-4c32-8f60-4114294029ba

**Comment by GrPK** [comment]
OK, I found the problem. The tab-shapes in Extras-Tabe Shape is at fault, when I use the one from zip everything works, but when I overwrite it with the one provided in the Tabe Shape menu the bug appears. Sorry, my fault. Thanks for your time

**Comment by Godiesc** [comment]
I forgot to delete that file in tab-shapes folder, my mistake, now I did it. Thanks for the report. 🤝
