### ISSUE TITLE
Application menu block the Menu button while in full screen

### ISSUE THREAD

**Issue by lhalic** [Godiesc/firefox-gx#105]
When you open the application menu, it blocks the menu button so you can not click it to close it again. This happens only in fullscreen mode.
![Screenshot_20231125_010913](https://github.com/Godiesc/firefox-gx/assets/128820061/abefe8b8-c487-43a6-b8e3-6b826325bb15)

This is release version of the code. And firefox version is 120.0.

**Comment by Godiesc** [comment]
hi,
in full-screen the hamburger-menu [open] should look like this:

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/eeed0241-24b6-4324-8268-3541de75b267)
 
what extra features you have activated and OS you are running?

**Comment by lhalic** [comment]
Only extra I have enabled is the Left Side-bar. I am running a Fedora KDE with plasma 5.27.9

**Comment by Godiesc** [comment]
maybe you are wrong, fullscreen is when you press f11,  you want to say that in maximized window you have that problem, but I just tested now in Manjaro-KDE and you can hide that menu from 1px on top and left side of the button, the trick to give that shape to the hamburger menu cause that problem, you can hide it pressing ESC too.

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/ee121544-bf0e-4f51-aeed-cbf6c49fc478)

and your button seems unaligned for some reason.

**Comment by lhalic** [comment]
You are correct. This happens on maximized window, now fullscreen. In fullscreen it works fine. But it seems that its not the button that is misaligned, but the menu itself. In your screenshot the menu is going to the edge of the firefox, but in mine its going few pixels below it, while the button remains where it should be. 

Also, are you saying you can not close it by clicking the Menu button again? You have to click somewhere else?

**Comment by Godiesc** [comment]
> Also, are you saying you can not close it by clicking the Menu button again? You have to click somewhere else?

when that menu is Opened the menu only can hide clicking on 1px on top or left, in the image I sent you can see where, you can hide it too when you clic in other part of the interfaz of the browser or pressing the ESC key.
