### ISSUE TITLE
Logo in left up corner isnt correctly coloured based on theme

### ISSUE THREAD

**Issue by T0biasCZe** [Godiesc/firefox-gx#107]
I installed the userchrome and the companion theme (choosed the blue one), but the logo in the upper left corner isnt coloured and is just black...
![image](https://github.com/Godiesc/firefox-gx/assets/44525446/f5047911-9699-44cc-90dc-01de7cce3fe7)
I tried both the latest master version from github, and also the version from the releases tab on github, neither doesnt work...

**Comment by Godiesc** [comment]
hi, for Firefox release version v.120 you should use the theme from "Releases" section, if you use beta or nightly maybe the code from `Code -> download` zip should work.

**Comment by T0biasCZe** [comment]
oops yeah i forgot copied the user.js file to the wrong folder 😅
