### ISSUE TITLE
one-line not working

### ISSUE THREAD

**Issue by Fyrnx** [Godiesc/firefox-gx#111]
after i updated firefox the one-line extra style does work any more the style is showing right but i can't use any tab or move them i tried to remove the style and firefox functions again i'm using it in nightly firefox update ( 123.0a1 )

**Comment by Godiesc** [comment]
thanks for the report, I hope to fix it when arrive to beta version.

**Comment by Godiesc** [comment]
@Fyrnx I hope the latest code (code->download zip) solve this problem, let me know if all works right.
