### ISSUE TITLE
tab line not working with most recent firefox update

### ISSUE THREAD

**Issue by boxxie79** [Godiesc/firefox-gx#112]
![image](https://github.com/Godiesc/firefox-gx/assets/88395316/914cebb5-f56c-4fdf-9816-cd864e763ca3)

**Comment by Ser4ph4** [comment]
Hello, look this > https://github.com/Godiesc/firefox-gx/discussions/110

**Comment by Godiesc** [comment]
@boxxie79 hello, with new Firefox update come new version of the theme, be sure to update it.
