### ISSUE TITLE
Tab shape sides don't appear on themes without a background

### ISSUE THREAD

**Issue by HTV04** [Godiesc/firefox-gx#115]
Not sure if this is just a configuration issue on my end, but the sides of tab shapes don't seem to work unless a theme with a background is used.

Default:
![image](https://github.com/Godiesc/firefox-gx/assets/53527582/6a488ad7-3a1d-4e1b-9c40-55bf6415aea1)
GX Fuchsia:
![image](https://github.com/Godiesc/firefox-gx/assets/53527582/897c62c6-3301-4ab5-877f-442d385e89b3)
Firefox Alpenglow:
![image](https://github.com/Godiesc/firefox-gx/assets/53527582/b3745b77-de4c-4e34-a2aa-8cffa1820598)
Red Blur:
![image](https://github.com/Godiesc/firefox-gx/assets/53527582/f723274d-cb04-45e5-9df6-7798143e072d)

These screenshots use the "Chrome" tab shape, but this occurs with every tab shape. I'm using Firefox 120.0.1 on Linux, if that helps.

**Comment by Godiesc** [comment]
Hi, be sure to use the theme version for your firefox version, if you use Firefox v.120 you should download the theme v.120.

**Comment by HTV04** [comment]
Hey, thanks for the quick response. I just updated to Firefox 121, but unfortunately, I'm still encountering the same issue:
![image](https://github.com/Godiesc/firefox-gx/assets/53527582/a66de864-4f46-482c-bf7e-be5b684ba944)

**Comment by Godiesc** [comment]
In the instructions of the theme said "use a compatible theme". The automatic theme is not compatible.

**Comment by HTV04** [comment]
I see, thanks for the heads up!
