### ISSUE TITLE
Window sometimes isn't clickable when starting the browser (can't double-click to fullscreen or drag the window around)

### ISSUE THREAD

**Issue by raw-binary** [Godiesc/firefox-gx#116]
I've been using this theme for a while now and an issue that I've encountered was that I can't drag the Firefox window by clicking at the top after launching the browser. The left sidebar is still clickable and can be dragged around, but not the top.
I usually fix this by focusing and unfocusing the window on Firefox a few times and it becomes clickable.

**Comment by Godiesc** [comment]
hi, I tried today to test that problem and I don't get it, I'm capable to move the window normally. Share with me the config you have, all the extras you are using, Operative system, to try to find out the problem. The theme is for release version of Firefox, if you use in other version maybe that is the problem.

**Comment by raw-binary** [comment]
It happens every time I start it up, provided the browser isn't maximized. There might also be an issue where you can click on it and drag it around just fine, but when you try to do it a second time it becomes no longer clickable.

I'm using Windows 10, with the following modifications:
- OneLine
- Main-Image
- Left Side-bar
- Classic Sound Icon

I'm using the unmodified `ogx_root-personal.css` file. One thing that might conflict with this is that I'm using [arkenfox's user.js](https://github.com/arkenfox/user.js) with the following overrides:

```
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("svg.context-properties.content.enabled", true); 
user_pref("layout.css.color-mix.enabled", true);
user_pref("browser.tabs.delayHidingAudioPlayingIconMS", 0);
user_pref("layout.css.backdrop-filter.enabled", true);
user_pref("browser.newtabpage.activity-stream.improvesearch.handoffToAwesomebar", false);
user_pref("privacy.userContext.longPressBehavior", 2);
user_pref("browser.startup.homepage", "about:home");
user_pref("privacy.window.maxInnerWidth", 1920);
user_pref("privacy.window.maxInnerHeight", 1080);
user_pref("browser.newtabpage.enabled", true);
user_pref("browser.startup.page", 1);
user_pref("privacy.resistFingerprinting.letterboxing", false);
```

Other than that, I'm not sure what else could be causing this.

**Comment by Godiesc** [comment]
I guess the "resistFingerprinting" is causing the window don't start maximized or the "window.maxInnerWidth" - "window.maxInnerHeight", I tested fast and don't get the problem, you should try to disable that preferences and test if that is causing it.

**Comment by raw-binary** [comment]
I tried removing the `window.maxInnerWidth`/`window.maxInnerHeight` attributes and they didn't seem to change anything. `resistFingerprinting.letterboxing` is false by default on Firefox and turning it on makes it spoof your browser resolution (arkenfox's user.js has it on, but for convenience i set it to off)

While messing around, I discovered that I can't drag the window by clicking on the red areas, but I can move it when clicking on the green. It might have something to do with it conflicting with the tabs bar.
![ex](https://github.com/Godiesc/firefox-gx/assets/155600866/eeaae9ff-45ed-43d5-a95d-42001e78d1bf)

**Comment by Godiesc** [comment]
mm, that seems to be the problem, "oneline" expand the toolbar (from search-box to buttons like the unified extension button) behind the tabs-bar, an maybe that trick cause that problem, I open the browser always maximized so I don't suffer that bug. you must get used to move your windows from the green part.

**Comment by Godiesc** [comment]
I tested again and the drag zone on the "red" area isn't clickable when the url is focused, in normal and maximized window, and I don't know if that could be solved or not. for example,

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/1ee9a93c-0377-4b52-9724-5084e77434ba)

@raw-binary  when you found that problem your url were focused?

**Comment by raw-binary** [comment]
Upon further testing, yes, it seems to happen when the URL is focused.

**Comment by Godiesc** [comment]
@raw-binary I updated the file [ogx_oneline.css](https://github.com/Godiesc/firefox-gx/blob/main/chrome/components/ogx_oneline.css) to solve this bug, hope you can test it.

**Comment by raw-binary** [comment]
It looks like that solved it. Thank you.

**Comment by Godiesc** [comment]
thanks to you for the report. 💙
