### ISSUE TITLE
Tab line issue on macOS

### ISSUE THREAD

**Issue by Tintouin** [Godiesc/firefox-gx#117]
As you can see there 

<img width="333" alt="Capture d’écran 2024-01-07 à 15 40 47" src="https://github.com/Godiesc/firefox-gx/assets/82973239/de69722f-7fb0-4e63-a5d7-fd1a0dc71216">   
The line is not properly finished. It was on installation and the first time I set up the left bar, but upon relaunching it stopped working. 

How can I fix his issue ?

**Comment by Godiesc** [comment]
hi, sorry for that bug, I'm currently updating the theme to solve various issues, with the actual version of firefox I changed the way that line display but is so inefficient.
for now you can add this code into `components/ogx_tricks.css` file:

```
#TabsToolbar::before{
        content: "" !important; position: absolute !important; align-self: end !important;
        width: var(--padding-left-tab, 0px) !important;
        height: 1px !important;
        min-height: 1px !important;
        max-height: 1px !important;
        left: 0 !important;
        width: 40px !important;
        border-bottom: 1px solid var(--general-color) !important;
    }
```

**Comment by Tintouin** [comment]
> hi, sorry for that bug, I'm currently updating the theme to solve various issues, with the actual version of firefox I changed the way that line display but is so inefficient. for now you can add this code into `components/ogx_tricks.css` file:
> 
> ```
> #TabsToolbar::before{
>         content: "" !important; position: absolute !important; align-self: end !important;
>         width: 40px !important;
>         height: 1px !important;
>         min-height: 1px !important;
>         max-height: 1px !important;
>         left: 0 !important;
>         width: 40px !important;
>         border-bottom: 1px solid var(--general-color) !important;
>     }
> ```

I did exactly this nothing has changes even after releaunch. I believe its due to some change I did since it wasn't always there...

**Comment by Godiesc** [comment]
sorry, I don't have mac and cant tested before give you the code, but I think it works but with a higher number of the with number, try something like this: 

```
#TabsToolbar::before{
        content: "" !important; position: absolute !important; align-self: end !important;
        height: 1px !important;
        min-height: 1px !important;
        max-height: 1px !important;
        left: 0 !important;
        width: 140px !important;
        border-bottom: 1px solid var(--general-color) !important;
    }
```

**Comment by Tintouin** [comment]
> sorry, I don't have mac and cant tested before give you the code, but I think it works but with a higher number of the width number, try something like this:
> 
> ```
> #TabsToolbar::before{
>         content: "" !important; position: absolute !important; align-self: end !important;
>         height: 1px !important;
>         min-height: 1px !important;
>         max-height: 1px !important;
>         left: 0 !important;
>         width: 140px !important;
>         border-bottom: 1px solid var(--general-color) !important;
>     }
> ```

Okay I didn't noticed that the width parameter could have an effect.
 
 So `140px`  were a bit too much:
 <img width="308" alt="Capture d’écran 2024-01-07 à 17 22 16" src="https://github.com/Godiesc/firefox-gx/assets/82973239/959c1373-d9c5-4cbc-8127-a97a8a0fc70c">
 
 I've set it to `100px` but it still wasn't perfect:
<img width="164" alt="Capture d’écran 2024-01-07 à 17 22 51" src="https://github.com/Godiesc/firefox-gx/assets/82973239/b43508e2-2377-4e1d-ad31-72c3dfa9d06f">
As you can see there is one pixel that breaks the outline here it is zoomed out:
<img width="62" alt="Capture d’écran 2024-01-07 à 17 29 12" src="https://github.com/Godiesc/firefox-gx/assets/82973239/04a68ac0-a44c-4e6f-abf7-68f015498898">

So I've set it at `99px` which was perfect:
<img width="134" alt="Capture d’écran 2024-01-07 à 17 39 08" src="https://github.com/Godiesc/firefox-gx/assets/82973239/81016bc6-cb40-4e5d-8882-a5a81a3e4750">

I think that you can commit this modification for mac since it not only fixed the left-sidebar version but it also fixed the default settings:
<img width="150" alt="Capture d’écran 2024-01-07 à 17 31 35" src="https://github.com/Godiesc/firefox-gx/assets/82973239/edfa2237-a55c-4a7e-a340-c8f3314a313c">
to
<img width="311" alt="Capture d’écran 2024-01-07 à 17 40 54" src="https://github.com/Godiesc/firefox-gx/assets/82973239/60fb1000-0e6b-45eb-b471-dff168b4c906">


My code is:
   ```
#TabsToolbar::before{
      content: "" !important; position: absolute !important; align-self: end !important;
      height: 1px !important;
      min-height: 1px !important;
      max-height: 1px !important;
      left: 0 !important;
      width: 99px !important;
      border-bottom: 1px solid var(--general-color) !important;
  }

```

I only changed the width

**Comment by Tintouin** [comment]
Also if you're looking for a macOS tester I can provide useful infos on beta and settings, I plan to port my TF2 GX mod (https://store.gx.me/mods/qujam3/tf2-natural-gx-mod/) to firefox through your addon and a few other extensions so I'll be messing around with it quite a bit and I was following your project for quite a long time now. You can email me anytime I guess.

I can on a much less frequent extent provide test for linux distros, just ask me.

**Comment by Godiesc** [comment]
thanks for testing the code, I will update the code in a few minutes so I would like you to test it from `code -> download zip`

**Comment by Tintouin** [comment]
Thank you, I'll certainly give more feedback since im now using firefox GX as my daily browser.

**Comment by Godiesc** [comment]
I updated the theme, and I would like to know too how looks the contextual menu with the icons added in this new release, you can disable the icons with this in `about:config `it the contextual menu becomes weird:

`firefoxgx.icon.disabled`

**Comment by Tintouin** [comment]
Nothing seems to have changed, even with the config, what is the expected behavior ?

Also, we should open a discussion about macOS compatibility to exchange about tests and everything rather than in this issue.

**Comment by Godiesc** [comment]
for example the menu in windows and linux looks like this:

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/1d979bd1-13e5-44db-a581-f226634135e3)

and I will create the discussion jut now.
