### ISSUE TITLE
Where is the left side bar download?

### ISSUE THREAD

**Issue by chez-dip** [Godiesc/firefox-gx#120]
I want to download the left side bar but can't find the download link. Is it missing or is there another way to download it? Please help me.

**Comment by Godiesc** [comment]
hi, the left-sidebar is the bookmarks-bar positioned on the side, you have the steps to apply in this link: [Left-SideBar](https://github.com/Godiesc/firefox-gx/tree/main/Extras/Left-SideBar)

**Comment by chez-dip** [comment]
ok thank you

**Comment by chez-dip** [comment]
Sorry to disturb you again but I've done all the steps and still haven't gotten the left sidebar. Did I do something wrong?
![Screenshot 2024-01-07 140607](https://github.com/Godiesc/firefox-gx/assets/118576898/e07919eb-c385-4914-8f3f-660437b0d400)

**Comment by Godiesc** [comment]
mmm, are you using the release version of firefox (v.121) and you downloaded the theme from the release section (v.121)?

**Comment by chez-dip** [comment]
no im using 4.0v because in the other versions, you can't change the wallpaper.

**Comment by chez-dip** [comment]
the one thats made in May 31, 2022

**Comment by Godiesc** [comment]
in all the version you can change the wallpaper, in the actual version you have the wallpaper images in a separate folder, and you can add your own images too.

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/6035e268-3078-4d9d-9f6f-af28c9997941)

maybe you don't know how to do it?

**Comment by Godiesc** [comment]
for change the wallpaper you should edit the code `chrome/components/ogx_root-personal.css` lines: 19 and 24.

**Comment by chez-dip** [comment]
i thought u needed to put the wallpaper name at ogx_userContent-personal

**Comment by Godiesc** [comment]
I made `ogx_root-personal.css` accessible for content too, so works flawless.

**Comment by chez-dip** [comment]
oh ok thanks i will try it

**Comment by chez-dip** [comment]
Did I edit correctly 
![Screenshot 2024-01-07 150309](https://github.com/Godiesc/firefox-gx/assets/118576898/7d68fc39-932e-46a7-9b8a-650ab14b4f46) because when I did it it showed no wallpaper like this 
![Screenshot 2024-01-07 150331](https://github.com/Godiesc/firefox-gx/assets/118576898/0f2860c0-b82a-4561-8184-c3130518817d)

**Comment by chez-dip** [comment]
in case you need it, this is the wallpaper i wanted
![Uploading wallpaper-dark16.png…]()

**Comment by Godiesc** [comment]
for this time pls download the theme from the button: `code -> download zip`, I updated the theme recently and for future reference you should do the next steps, the same just the newtab folder change its location, is so easy:
1.- Download the theme and move the chrome folder to your firefox profile folder (you did it so is not complicated jeje )
2.- Copy  the wallpaper you want to chrome/newtab folder:

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/faf709af-560e-4a56-8e53-e383db4cd206)

3.- change the line 16 with the name of your new image: 

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/93809691-039d-4777-921e-8ac55ed80dc3)
