### ISSUE TITLE
Spotify in sidebar like in OGX

### ISSUE THREAD

**Issue by Tintouin** [Godiesc/firefox-gx#126]
I found several tools and miniplayer for Spotify, but none are like small Spotify wrapper that are in the sidebar, they're all miniplayers that requires you to open a window for it. 

I saw @Godiesc developed some of the sidebar extensions he provides, I'm requesting it for later.

**Comment by Tintouin** [comment]
On opera
<img width="1792" alt="Capture d’écran 2024-01-10 à 22 12 15" src="https://github.com/Godiesc/firefox-gx/assets/82973239/345c424b-b338-4518-bc9a-9ef574fad110">
Best I could find for Firefox
<img width="715" alt="Capture d’écran 2024-01-10 à 22 12 43" src="https://github.com/Godiesc/firefox-gx/assets/82973239/094b3076-eea4-4af1-a99a-32b505a665cf">

**Comment by Godiesc** [comment]
hi, Would be possible to add that extension but unfortunately you will need to keep open the sidebar while listen your music cause Firefox AFAIK can't keep opened the site when you close that sidebar.

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/805c4efd-9100-4ade-8d62-807a03d643e9)

**Comment by Godiesc** [comment]
@Tintouin Extension ready: https://addons.mozilla.org/es/firefox/addon/spotyplay-in-sidebar/
