### ISSUE TITLE
accent color change - settings page wallpaper - bookmarks

### ISSUE THREAD

**Issue by Makezu90** [Godiesc/firefox-gx#127]
Nice theme, but how i can see my bookmarks on top bar bottom address bar? How about change accent color white to another example red? did not saw any option is CSS. how about change wallpaper in settings page?

**Comment by Godiesc** [comment]
> Nice theme, but how i can see my bookmarks on top bar bottom address bar?

hi, I don't understand what this mean.

> how about change wallpaper in settings page?

that wallpaper is the same from new-tab page, if you want a different wallpaper it's possible changing the link in `UC-settings-addons-pages.css`: [this line](https://github.com/Godiesc/firefox-gx/blob/main/chrome/components/ogx_UC-settings-addons-pages.css#L354) 
to something like this: 
`--bg: url("../newtab/minuevaimagen.png");`

**Comment by Makezu90** [comment]
i mean this: 

i uninstalled theme now, because can't find way to show it this way, also if i put these links to sidebar, it looks very ugly, also there was other bookmark option, but need to click atleast 3 times get these bookmark links.. so yeah. if there is anyway get bookmarks to that way with sidebar let me know, otherwise i try find better theme.

![kuva](https://github.com/Godiesc/firefox-gx/assets/89158176/d9c9d957-2ed4-4e3d-aa4b-2805ebb4f562)

**Comment by Godiesc** [comment]
Sorry, I cant understand you, hope you find the perfect theme for you. The theme shows the bookmarks like always, and if you try the "left-sidebar" config of my theme, that just move that bar to the left and you can use your bookmarks like always.
Good luck. 💚
