### ISSUE TITLE
Help with URL bookmark icons color

### ISSUE THREAD

**Issue by soilentgreen** [Godiesc/firefox-gx#128]
Hi @Godiesc ,
I use LibreWolf 121.0-1, and I like to know if you can help me to find a way to color the URL bookmark icon to red.

Thanks :-)

![111111](https://github.com/Godiesc/firefox-gx/assets/7990597/183db201-0e6d-4483-b83a-9bfd5e5dc958)

**Comment by Godiesc** [comment]
Hello, I don't think there is a simple way to do that, that icon is provided by the website, so you can change it, but you have to do it for each bookmark. I found this way in [[reddit](https://sh.reddit.com/r/FirefoxCSS/)](https://sh.reddit.com/r/FirefoxCSS/comments/iezs1a/change_icon_for_those_bookmarks_without_favicon/)

1.- I first search for an image for amazon here: https://iconduck.com/icons/2881/amazon-square.
2.- I edited that image code to add the property `fill="context-fill"` to give the image the color of the theme.

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/92f79c7d-f652-4157-821a-74bf21e20747)

3.- Add the image into `chrome/icons` folder.
4.- Into the file `ogx_tricks.css` add the next code:

```
.bookmark-item[image*="page-icon:https://www.amazon.com"]>.toolbarbutton-icon {
        width: 0px !important;
        height: 0px !important;
        padding: 0 0 18px 18px !important;
        background-image: url("../icons/amazon-square.svg") !important;
        background-size: cover !important;
    }
```

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/d938ad05-e154-46e2-94d5-1b5e52e53b1d)

**Comment by soilentgreen** [comment]
Many thanks, It worked like a charm :-)
Can I ask another help?
There is any way to color the tabs webs icons to red as-well? 

![222](https://github.com/Godiesc/firefox-gx/assets/7990597/82b5d293-7430-4861-90dd-4cd15c628cc0)

**Comment by Godiesc** [comment]
for the new-tab favicon I use this, I wonder why librewolf change it:

```
/* Favicon de pagina newtab */

.tab-icon-image[src="chrome://branding/content/icon32.png"] {
    content: url("../icons/foxlogofavicon.svg");
    fill: var(--identity-icon-color, var(--general-color)) !important;
}
```
for the sites favicon I don't know how to do that, maybe you should ask in https://sh.reddit.com/r/FirefoxCSS/ to see if is possible i some way.

**Comment by soilentgreen** [comment]
Thanks again @Godiesc  for your help. It worked :-)
For the sites favicon I'll ask in reddit as you suggested.

**Comment by soilentgreen** [comment]
@Godiesc , I don't know if it something you want to use in your theme, but the user ilovebmo01 give me this code:

`.tabbrowser-tab .tab-icon-image { filter: sepia(1) saturate(5000%) hue-rotate(0deg); } `

[https://www.quackit.com/css/functions/css_hue-rotate_function.cfm](url)

And it's partially succeeded. All the webs icons with one color as github, virusetotal...are colored in red, but all the webs with more than one color as google, amazon.. are colored partially in red. It as like this code can color only one color of the icon.

Just so you know.

**Comment by Godiesc** [comment]
thanks for sharing, I didn't consider that cause the favicon is essential to distinguish the tab, and make it just 1 color or similar can do confusion.
