### ISSUE TITLE
help

### ISSUE THREAD

**Issue by tank-sman** [Godiesc/firefox-gx#129]
How to remove these icons?
I did it one time, but now don't know how to do it.

![image](https://github.com/Godiesc/firefox-gx/assets/65546026/e122bef3-4ac2-4a9d-b931-b17566157152)

**Comment by Godiesc** [comment]
you have that information in the release notes of the theme:

`firefoxgx.icon.disabled` | `true`

**Comment by tank-sman** [comment]
My brain burned that I thought where did I see it.
Thanks a lot.
