### ISSUE TITLE
A certain problem with tabs

### ISSUE THREAD

**Issue by Exorcism0666** [Godiesc/firefox-gx#130]
I don't know why it's red like that, I've just updated the pack and this is what happens 😭.
![image](https://github.com/Godiesc/firefox-gx/assets/46537034/01ef29b6-401c-4539-be7b-1fbe2a36bed9)

**Comment by Godiesc** [comment]
some problems happens with the recent updated for Firefox for that reason you should use the correct version of the theme for your version of Firefox, if you use Firefox 121.0.1 be sure to use the v.121.0.1 of the theme, there is the "Releases" section toy choose the right files. If you use beta or nightly version maybe should work the code from `code->download zip` but it's not "always".
If you still have the problem pls share information of you Firefox versions, theme in use, your OS, and if I could test it maybe I can resolve your problem.

**Comment by Exorcism0666** [comment]
It's true that I completely forgot to update Librewolf, I'll do it right away.
