### ISSUE TITLE
Just a little enhanement but could you make the Tree Style Tabs and Bitwarden extention the color of your chosen color?

### ISSUE THREAD

**Issue by chez-dip** [Godiesc/firefox-gx#131]
I put Tree Style Tabs and Bitwarden extension in my left side bar but it is the only icons on my sidebar that isn't my chosen color. Could you please fix this?

**Comment by Godiesc** [comment]
It's difficult to add a icons with the property 'fill' for every extension of the browser; the ideal could be every user update the code to add the necessary code and icon for its personal extensions 😀
