### ISSUE TITLE
Is there a way to make the Left Sidebar Extensions display as an overlay instead of split screen?

### ISSUE THREAD

**Issue by Tripp1e** [Godiesc/firefox-gx#132]
Currently, when you open the extensions they display as a whole new site instead of like in actual opera GX, where they are a mini overlay and now I was wondering if there is a way to make them like that
Instead if this:
![grafik](https://github.com/Godiesc/firefox-gx/assets/102437240/c067632d-a758-4723-be0c-9ec01d6b9753)
this:
![grafik](https://github.com/Godiesc/firefox-gx/assets/102437240/73bb56e3-c84d-4c7a-84b6-23d3ce92c342)

**Comment by Godiesc** [comment]
hi, you can get with some css:
-'expand on hover' sidebar.
- Maybe something like you requirement, but the sidebar must be close to see the web content every time.

The features of Opera-GX are in Opera-gx jeje, I just try to make a similar theme but that's all.

**Comment by Tintouin** [comment]
> hi, you can get with some css: -'expand on hover' sidebar.
> 
>     * Maybe something like you requirement, but the sidebar must be close to see the web content every time.
> 
> 
> The features of Opera-GX are in Opera-gx jeje, I just try to make a similar theme but that's all.

You should keep a note about this in the extension's help so people can modify it to their likings

**Comment by Godiesc** [comment]
I mean I give you some possibilities to do with css but I didn't implemented to this theme or something like that, in the [firefoxcss community ](https://sh.reddit.com/r/FirefoxCSS/) you can ask or find some code to use.

**Comment by Tintouin** [comment]
> I mean I give you some possibilities to do with css but I didn't implemented to this theme or something like that, in the [firefoxcss community ](https://sh.reddit.com/r/FirefoxCSS/) you can ask or find some code to use.

I get this, even if mimicking completely OGX is not your objective, as more and more people switch from OGX to FGX you should let them easily keep some senses, and responsivity, a bit more than the layout and newtab page. Don't you think ?

**Comment by Godiesc** [comment]
within the possibilities that Firefox allows, yes, for now I was working in an extension for easy change of theme and easy change of accent-color, could be useful:

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/595996c8-e08c-40a3-8415-ed72890dfd22)

**Comment by Tintouin** [comment]
> within the possibilities that Firefox allows, yes, for now I was working in an extension for easy change of theme and easy change of accent-color, could be useful:
> 
> ![imagen](https://private-user-images.githubusercontent.com/22057609/298291877-595996c8-e08c-40a3-8415-ed72890dfd22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NjUwODYsIm5iZiI6MTcwNTc2NDc4NiwicGF0aCI6Ii8yMjA1NzYwOS8yOTgyOTE4NzctNTk1OTk2YzgtZTA4Yy00MGEzLTg0MTUtZWQ3Mjg5MGRmZDIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDE1MzMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZjM5NjZlYWY4MmVkZmRhNDY5NzQyZDQ2NGJjNTliOGM3MjMxYmUxOTQyN2FhY2U5YzgxZDUzNjhhZjMxMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2GFWicSurJFL7scjtdmxSvoV6aH1FnOfQkjwR3kuN-Y)

Damn ! AWESOME as usual ! You should add some objectives and milestones so community could actually help you, or at least know what's planned. Good luck.
