### ISSUE TITLE
My left panel is not showing when I'm on the site

### ISSUE THREAD

**Issue by FlyingHermes** [Godiesc/firefox-gx#133]
When I go to the site, its borders overlap my left panel

![изображение](https://github.com/Godiesc/firefox-gx/assets/79836672/90686be1-7ea1-4ccd-9f72-fc089385c5cb)

![изображение](https://github.com/Godiesc/firefox-gx/assets/79836672/b6a2053d-d8b4-4764-bea9-3f7c99998704)

**Comment by Tintouin** [comment]
This left panel needs to be configurated with the extra left sidebar, you can find more in https://github.com/Godiesc/firefox-gx/tree/main/Extras/Left-SideBar

**Comment by FlyingHermes** [comment]
I was very inattentive, my problem is solved. 

 You just had to turn on the "always show" feature."

![изображение](https://github.com/Godiesc/firefox-gx/assets/79836672/f94a2337-52dd-47b9-ab93-90db07c77978)

**Comment by Godiesc** [comment]
I aw your selected tab with a bug in the image, rare, I tested it again an for me looks right.

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/c74c4006-03dc-4529-9ccf-c947d635db8d)
