### ISSUE TITLE
 help with v.122

### ISSUE THREAD

**Issue by soilentgreen** [Godiesc/firefox-gx#136]
Hi @Godiesc ,

The new update broke some stuff can you please help me?

1 The checkbox check was black now its white. how can I make it black?
the code 
`--checkbox-checked-color: black !important;`
In ogx_notifications.css not working.

2 The same as 1, the code in ogx_UC-settings-addons-pages.css is not working. there is a lot changing in the code and I can't understand what need to be done for change the checkbox check to black.

3 The LibreWolf  icon  CAN color to red or replaced?

Thanks again :-)

![1](https://github.com/Godiesc/firefox-gx/assets/7990597/e8fb844b-67e3-41e7-bb25-bdc6ed2ac14c)

![2](https://github.com/Godiesc/firefox-gx/assets/7990597/bb785f8b-3a37-4dfb-9928-011cbd575c19)

**Comment by Godiesc** [comment]
hi, the check-box now seems to follow the system UI or something like that, I tried to change that colors and fail.

**Comment by soilentgreen** [comment]
Thank you very much for answered.
I try my luck with reddit, hope someone will find solution.

**Comment by Godiesc** [comment]
hi again, you can try asking in this page, the master is there to answer any question: https://lemmy.world/c/FirefoxCSS@fedia.io

**Comment by soilentgreen** [comment]
@Godiesc  Hi,  just now I saw your comment. Thank you very much for the link. I will ask there. If he manages to solve the problem, I'll let you know.

**Comment by soilentgreen** [comment]
@Godiesc  So as you say he is a master. He fix it :-) 
https://lemmy.world/post/12613564

What I did if you like to know:

in ogx_notifications.css
under:
`@-moz-document url(chrome://global/content/commonDialog.xhtml),
    url("chrome://mozapps/content/handling/permissionDialog.xhtml"),
    url("chrome://mozapps/content/handling/appChooser.xhtml")
{
    #commonDialogWindow,
    #commonDialogWindow * {`


I deleted  ` --checkbox-checked-hover-bgcolor: var(--general-color) !important;`

and put in the end:

`.checkbox-check{
    appearance: none !important;
    background: #A21E1E;
}`

`.checkbox-check:hover{
  background: #ff0000;
}`

`.checkbox-check[checked]{
    background-image: url("chrome://global/skin/icons/menu-check.svg");
  }
}`

In ogx_UC-settings-addons-pages.css
I put in the fist line:

`@-moz-document url-prefix("about:preferences"){`

`.checkbox-check{
    appearance: none !important;
    background: #A40000;                                                                                      
} `

`.checkbox-check:hover{
  background: #ff0000;
}`

`.checkbox-check[checked]{
    background-image: url("chrome://global/skin/icons/menu-check.svg");
  }
}`

**Comment by Godiesc** [comment]
excellent, glad you solve your request, for ogx default style I don't need to change that, but if I need it in the future I will know how to change that, thanks.
