### ISSUE TITLE
Themes: Icon color not working on Linux/Ubuntu

### ISSUE THREAD

**Issue by TekPike** [Godiesc/firefox-gx#137]
I'm using "GX Theme Styles", and icons color isn't working.

I'm on Ubuntu 22.04.3 LTS (Wayland) - Firefox 122.0 (64 bits).

![Screenshot here](https://github.com/Godiesc/firefox-gx/assets/19296855/609a58c2-6edf-4196-a059-7b974c0affd8)

**Comment by Godiesc** [comment]
hi, be sure to paste the `user.js` file into your profile folder or active manually all the preferences of the file in `about:config` page.

**Comment by TekPike** [comment]
Fixed!
(sorry for the inconvenience, I first installed it on my Windows PC following the tutorial, and then on my Linux PC... and I forgot this script. Thanks for your quick answer and great work!)
