### ISSUE TITLE
set main image

### ISSUE THREAD

**Issue by EnheGD** [Godiesc/firefox-gx#142]
I really don't get it at all

**Comment by Godiesc** [comment]
hi, you should show a screenshot to see how the theme looks for you. the instructions are in the link for that config.

**Comment by EnheGD** [comment]
![Captura de pantalla 2024-02-13 205414](https://github.com/Godiesc/firefox-gx/assets/136941627/bdc36e2b-0ff1-4c37-b449-fbe63f727533)
how do you customize the main image

**Comment by Godiesc** [comment]
for example in windows I open the image I want to use in the program 'photos', and resize the image with the size of my monitor.
Here you have a previews questions about that: https://github.com/Godiesc/firefox-gx/discussions/121
