### ISSUE TITLE
Bug (?) with NewTab Wallpaper

### ISSUE THREAD

**Issue by GrPK** [Godiesc/firefox-gx#145]
Hello, regarding second option when trying to change the NT wallpaper, if I edit the lines 19 and 24 with the new wallpaper name (let's say, for example wallpaper-dark5.png), the wallpaper-dark.png will still be applied. Changing the name of the ...5.png to wallpaper-dark.png fixes the issue.

So the problem is that you cannot put another name except  wallpaper-dark.png wallpaper-white.png and not something like YourName.png?

**Comment by GrPK** [comment]
What I tried to say is that only Option 1 is working, but not Option 2 when I want to put a png with a specific name

**Comment by Godiesc** [comment]
hi, changing the name in the code should work, you can use other name and file extension like 'yourname.png', 'yourname.jpg', 'yourname.gif' or the image you want, be sure your image is in 'newtab' folder and restart the browser if you are not editing the file with the console.

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/b7efa4d9-4012-4593-ae84-f787206f5725)

**Comment by Godiesc** [comment]
I'll assume your problem is resolved.
