### ISSUE TITLE
Impossible to interact with a part of the oneline

### ISSUE THREAD

**Issue by xav35000** [Godiesc/firefox-gx#146]
Hi 👋 
I've been using Firefox GX for a month and I'm really happy with it, but, recently, the oneline stopped working (see screenshot).

I'm using Librewolf based on version 123.0-1 of Firefox.

![Capture d’écran 2024-02-25 185529](https://github.com/Godiesc/firefox-gx/assets/95582771/a79d863f-5d99-4a20-95dd-4b817c1fdc36)

**Comment by Godiesc** [comment]
Hi, be sure to update your theme to the latest version from the 'release' section.

**Comment by xav35000** [comment]
Thank you, sorry for the inconvenience, I'm really dumb... 😆
