### ISSUE TITLE
(Left-sidebar) Add ability to change/make sidebar icons 

### ISSUE THREAD

**Issue by UsernameAdamGits** [Godiesc/firefox-gx#147]
Nothing much to this one. The ability to change icons used in sidebar. Also make ones for non-supported extensions like Gmail Sidebar.
Thanks.

**Comment by Godiesc** [comment]
hi,
I should add information to change that, you will need to get the new icon (.svg) and added the `fill="context-fill"` property and add some code to `ogx_tricks.css`, I will add it in tricks section I guess.

**Comment by UsernameAdamGits** [comment]
alright, thanks!

**Comment by Godiesc** [comment]
@UsernameAdamGits hi, sorry for the time taken to make this request, I added the information in a [discussions](https://github.com/Godiesc/firefox-gx/discussions/157) with the steps to follow, I hope you find it useful.

**Comment by UsernameAdamGits** [comment]
Thanks!
