### ISSUE TITLE
popups border has shown up in the new nightly versions

### ISSUE THREAD

**Issue by Fyrnx** [Godiesc/firefox-gx#149]
i updated nightly about 2 day ago and some codes stop working i found that 

`lift-sidebar`: now has a transparent background the

`one-line`: still not working properly ( i fixed some bugs in it manually before but it showed more bugs after the update ) 

and the more important thing is that now there is a huge white border in every popup 
i tried to remove it by this code

```css
panel.panel-no-padding::part(content) {
  border: none !important;
}
```

the strange thing is this code works when trying it in the developer tools in a `inline-style` but when i added it to the custom codes in the addon it didn't work 

the new version of nightly is `Nightly 126.0a1 (20240319215652)`

**Comment by Godiesc** [comment]
Thanks for the report, I checked and a lot of bugs appeared in Nightly, hope all have solutions.

**Comment by Godiesc** [comment]
@Fyrnx I updated the theme, you can tested from `code->download zip` to see if all the problems are solved.

**Comment by Fyrnx** [comment]
it didn't fix the main problem for me the white border around the popups but i think its a problem in my side or one of the addons i have 

can you give me the code for the tabs style only

can you provide the documentation for how to make custom style like this
because i don't know how to use @media (-moz-bool-pref) probable and is there something like for string and numbers

**Comment by Godiesc** [comment]
mm, I tested and seems right, I don't know if an extension can make that issues, but I don't know.

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/d92f7355-c0d0-4c03-9b92-e44fbdd17233)


> can you give me the code for the tabs style only

the problem with Nightly version was some global selector so I don't make big changes into specific styles to solve those problems, I don't know what tab style you ask.

> can you provide the documentation for how to make custom style like this

I don't know what you mean with this.

**Comment by Fyrnx** [comment]
are there any documentation for how to make custom userChrome because there is some features not in normal css

**Comment by Godiesc** [comment]
I don't get it, for your custom css you can add it into `chrome/components/ogx_tricks.css` file, for activate "Extra" features you have links with the steps to do.

**Comment by Fyrnx** [comment]
can you just explain this code
```
@media (-moz-bool-pref:"firefoxgx.left-sidebar") {}
```

i know it checks if the value of  `firefoxgx.left-sidebar` in the `about:config` is true if it's true it runs the codes 

so if the `firefoxgx.left-sidebar` was a string how can i use `@media` to check it's value

if your are not sure what this code does or what i mean no problem use solved the main issue so i will just close this issue

**Comment by Godiesc** [comment]
mm, that check is made for the browser, for example in this new example the code is run when the first is true and the second is false, you have extended info in interet for example here: [@media queries](https://developer.mozilla.org/es/docs/Web/CSS/CSS_media_queries/Using_media_queries) or [@media w3school](https://www.w3schools.com/cssref/css3_pr_mediaquery.php)

`@media (-moz-bool-pref:"firefoxgx.tree-tabs") and (not ( -moz-bool-pref:"firefoxgx.oneline")){..}`
