### ISSUE TITLE
Sidebar Not appearing

### ISSUE THREAD

**Issue by GabrieleGiacomelli** [Godiesc/firefox-gx#150]
Hi nice to meet you and thank for your work
The only issue i have is the fact that the side bar is not appearing. To tell all the info i copyed the user,js info into the user,js from better fox. I don't know if is that the problem, but for anything else it work fine. What can i do? Did i skip an enable check?

**Comment by Godiesc** [comment]
hi, in git-hub main page you have the "Extras" section with the link for enable "left-sidebar", be sure to copy the content of my user.js at the end of your user.js from better fox.
