### ISSUE TITLE
Not working on linux

### ISSUE THREAD

**Issue by brotherman123** [Godiesc/firefox-gx#151]
after unzipping it in the ~./mozilla folder (which is the profile folder) than opening and closing firefox it did not work.

**Comment by Godiesc** [comment]
hi,
here you have a screenshot to find your profile folder: https://github.com/Godiesc/firefox-gx?tab=readme-ov-file#example-of-aboutsupport 

after that you follow the steps to apply the theme:

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/dcc5bdf0-1e6b-440c-8568-5e99b71a11b3)

**Comment by brotherman123** [comment]
![image](https://github.com/Godiesc/firefox-gx/assets/156553255/0cfe6f99-a712-4f91-815b-4b3b60eebdff)
no taskbar

**Comment by brotherman123** [comment]
sidebar fixed have a nice day thanks for the help!
