### ISSUE TITLE
Gaps between address bar and tabs in one line mode

### ISSUE THREAD

**Issue by kotobuki09** [Godiesc/firefox-gx#152]
Could you help me how to remove this space. Cause it's seem like unnecessary space that the we can delete it
[https://i.imgur.com/WCGDPl4.png](https://i.imgur.com/WCGDPl4.png)

**Comment by Godiesc** [comment]
hi, that style don't have that space, be sure to move out "flexible spaces" before apply the 'oneline' config, I give this screenshot to see how the buttons should looks like before apply that config.

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/e1d9552c-f36c-4577-9fa7-8192bf1222be)
