### ISSUE TITLE
Sidebar header not hidden

### ISSUE THREAD

**Issue by brunebug** [Godiesc/firefox-gx#153]
Tab Center Reborn sidebar not hidden when installing version 1.2.3. Firefox was updated to 1.2.4 not sure if that is the update that broke it. 
![header image](https://github.com/Godiesc/firefox-gx/assets/166668011/0ad16914-834a-40f2-8f0c-ad76e51dc9e9)

**Comment by Godiesc** [comment]
hi, I just tested and seems right, maybe you can try to update the [ogx_tree-tabs.css](https://github.com/Godiesc/firefox-gx/blob/main/chrome/components/ogx_tree-tabs.css) file and see if that solve your problem.

**Comment by brunebug** [comment]
unfortunately I think i bricked something I'm starting from scratch on a new firefox profile, I download [the version 9](https://github.com/Godiesc/firefox-gx/releases/tag/v.9.0) named FirefoxGX_Release_v.123.zip and then copy the user and the chrome folder to my profile correct? then just follow the steps on the extras tab?

**Comment by Godiesc** [comment]
Yes. You applied the theme before so is not different, just follow the steps for the config you want with the extension you use.

**Comment by brunebug** [comment]
Does it matter which order I install the "extras" in? I did the gx theme styles extension for the theme, not sure if that presented issues. Still trying to figure out github lol, i appreciate the quick support

**Comment by Godiesc** [comment]
the 'GX-theme-styles' extension is just for the colors and don't makes any issue, for the 'tab-center-reborn' extension just follow the steps and be sure you apply just the "extras" you want, for example if you apply the 'one-line' config and after that you try to apply the 'tree-tabs' config, that will not apply cause that styles are incompatible.

**Comment by brunebug** [comment]
OH, I have to apply tree tabs first, then one line? Or I cannot do both together

**Comment by Godiesc** [comment]
if you need the 'tree-tabs' config you don't need the 'one-line' config, why will you apply both?

**Comment by brunebug** [comment]
I really liked the way they both looked, I see what you mean though they both have the same functionality. I got it to work without online properly! Thank you so much for the prompt support. Much appreciated
