### ISSUE TITLE
Status bar visibility issue on dark theme

### ISSUE THREAD

**Issue by brunebug** [Godiesc/firefox-gx#154]
Im running into an issue where the tooltip/bar located on the bottom left of my screen that appears when you hover over a link isnt visible on webpages that are light. Is there a quick fix to this atm? I'm assuming its theme related but no matter which theme I select it doesn't seem to adjust. I'm attaching some screenshots that show what it looks like on a dark background/light background.
![Screenshot (18)](https://github.com/Godiesc/firefox-gx/assets/166668011/117f2004-1ddf-449c-9552-85ed7c352529)
![Screenshot (21)](https://github.com/Godiesc/firefox-gx/assets/166668011/b62e227f-4e4f-4725-b75e-5cd34d5eee2c)

**Comment by brunebug** [comment]
Edit: This is happening with the one-line config only. Tree tabs or default firefox gx has not had this issue

**Comment by Godiesc** [comment]
I updated the files for 'oneline' and 'Main-image' config to solve the problem, with the next release of the theme that problem will be solve or you can tested downloaing the theme from `code->download zip`.

**Comment by brunebug** [comment]
Download it on the main page correct? The green button on https://github.com/Godiesc/firefox-gx? So far everything’s worked with that update! Super great support as always thank you
