### ISSUE TITLE
Add GX Mods Extension Project To Extras!

### ISSUE THREAD

**Issue by Maxitendo1** [Godiesc/firefox-gx#155]
I just found another project which focuses on letting you download ambient music, typing sounds and more stuff from the GX store directly into Firefox. It's also open-source and on Github:

https://github.com/noblereign/GX-Mods-Extension

It would be great to integrate this into FirefoxGX or add it to Extras:

https://github.com/Godiesc/firefox-gx?tab=readme-ov-file#extras

![grafik](https://github.com/Godiesc/firefox-gx/assets/136966318/32d9fddf-205f-4f14-8000-07d277b2a837)
![grafik](https://github.com/Godiesc/firefox-gx/assets/136966318/109b3d9e-adc7-4c5f-a037-babf9bcd76b3)

**Comment by Godiesc** [comment]
hi, that extension was mentioned in one of the [discussions](https://github.com/Godiesc/firefox-gx/discussions), I should add the link in the release notes of the theme maybe to reach all the users.
