### ISSUE TITLE
New-Tab Scrolling

### ISSUE THREAD

**Issue by J-A-C-O** [Godiesc/firefox-gx#158]
![Screenshot 2024-05-01 230800](https://github.com/Godiesc/firefox-gx/assets/168699224/f4a37b40-eacd-4c33-b766-c9342479f7c3)

On the new tab page, I am able to scroll left and right on the search menu overlapping the photo. (Does not happen in private mode.)

**Comment by Godiesc** [comment]
hi, thanks for the report, this is a bug unsolvable for now, it appears when add the wallpaper, the solution could be delete the code for that but is not acceptable, Firefox is working on a native way to put a wallpaper so maybe in a future this will be solve.

**Comment by J-A-C-O** [comment]
Thanks for your quick response.

**Comment by J-A-C-O** [comment]
Thank you for addressing the problem. Have a great day.
