### ISSUE TITLE
Very minor clipping issue when on the first tab

### ISSUE THREAD

**Issue by just-a-github-user** [Godiesc/firefox-gx#160]
Very minor clipping issue on UI
![image](https://github.com/Godiesc/firefox-gx/assets/65435880/efb1ad04-6316-42e4-ab0d-44e1ad121677)

**Comment by Godiesc** [comment]
hi,
you should share you specific setting to test it right, Firefox version, theme version, etc, cause I tested and all seems right, in your screenshot seems like the tab line is bigger, like 2px and the default is 1px, are you sure you don't change that manually?

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/467b7a13-514d-4ce9-b816-3d4a69078025)

**Comment by just-a-github-user** [comment]
> hi, you should share you specific setting to test it right, Firefox version, theme version, etc, cause I tested and all seems right, in your screenshot seems like the tab line is bigger, like 2px and the default is 1px, are you sure you don't change that manually?
> 
> ![imagen](https://private-user-images.githubusercontent.com/22057609/330892188-467b7a13-514d-4ce9-b816-3d4a69078025.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3Mzg0MTksIm5iZiI6MTcyNzczODExOSwicGF0aCI6Ii8yMjA1NzYwOS8zMzA4OTIxODgtNDY3YjdhMTMtNTE0ZC00Y2U5LWI4MTYtM2Q0YTY5MDc4MDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDIzMTUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ZDgxYWJiODQ2NjFlZTM1MGU1NzM4OTg0ZWJlMjhjNzgzNWIzZWQ5N2IxZWYwMjllNWYxYmFhMmRmYTZhNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z2QsQyqTgUMoOUUWTuwVvanRJ7J8JempRhDCrR2C12Y)

Hey, been a few months, but I figured out the cause of this bug. If the Scale of apps in the windows settings is set to 150% the clipping seems to occur. Setting it to 125% seems to fix it.

**Comment by Godiesc** [comment]
hi, I didn't test the theme in other WindowsOS scales, and I don't think I could make compatible with that, thanks for share your solution.
