### ISSUE TITLE
Toolbar Issue

### ISSUE THREAD

**Issue by njian0** [Godiesc/firefox-gx#161]
Hey there!

I know I'm using an outdated version of this mod on the latest FireFox, but I have ran into a bit of a problem. (Screenshot attached.)

Is there any way I can fix this issue? Or do I need an outdated version of Firefox?

I'm using the "Firefox GX theme to Firefox release v. 103."

Thanks,
njian0
![image](https://github.com/Godiesc/firefox-gx/assets/167185483/675f391e-1913-4ba5-84b2-d12175b002d6)

**Comment by Godiesc** [comment]
hi, the latest release of the theme ([FirefoxGX_Release_v.125](https://github.com/Godiesc/firefox-gx/releases/tag/v.9.1)) works for Firefox 125-126 without problems, If you use a older Firefox version you can try to search the theme for that version, the information in the readme in github works in the release version of Firefox.

> I'm using the "Firefox GX theme to Firefox release v. 103."

do you said you are using Firefox v.103, so the theme you should download is this: https://github.com/Godiesc/firefox-gx/releases/tag/v.5.0

**Comment by njian0** [comment]
Sorry, I think there is an misunderstanding. 

> do you said you are using Firefox v.103, so the theme you should download is this: https://github.com/Godiesc/firefox-gx/releases/tag/v.5.0

The file that I am using **is** the Firefox GXv.5.0, but I have the latest version of firefox.

What do I need to change in the code to fix the menu? Or do I need an outdated version of firefox?

Thanks,
njian0

**Comment by Godiesc** [comment]
if you use the latest Firefox release version you should update the Firefox-GX theme to the latest version too, maybe you are not updating cause you did some personal changes to the theme?
I recommend you to update the theme, this is the latest code to Firefox v.125-126: https://github.com/Godiesc/firefox-gx/releases/tag/v.9.1

**Comment by njian0** [comment]
Okay, thank you for helping.

Love the theme by the way! :D
