### ISSUE TITLE
Bookmark not showing bookmarks

### ISSUE THREAD

**Issue by Kaixvny** [Godiesc/firefox-gx#163]
I have left.sidebar set to true, and i have do have bookmarks but theyre not showing up on it.
![image](https://github.com/Godiesc/firefox-gx/assets/68577140/49a0e987-23b4-47af-adb6-4c1edca02cd6)

**Comment by Godiesc** [comment]
hi,
for 'bookmark items' be sure to have this icon in the bookmark bar:

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/35af3e1a-6d96-4c75-b30f-0608358d9d66)
