### ISSUE TITLE
New Firefox update broke gx

### ISSUE THREAD

**Issue by Crrene-p** [Godiesc/firefox-gx#164]
![Screenshot 2024-05-16 233031](https://github.com/Godiesc/firefox-gx/assets/156001122/f61dbdbc-3846-4e3c-a873-8066fc1a4abd)
The new Firefox update broke the look I had. The functionality is still there, but it looks very ugly in my opinion

**Comment by Godiesc** [comment]
hi,
if you are using the release version of Firefox download the [latest version of the theme](https://github.com/Godiesc/firefox-gx/releases/tag/v.9.1) from the release section, I tested and works fine. If you are using the beta/nightly version maybe you could see a little bugs and I hope to solve them soon.
