### ISSUE TITLE
Firefox 126.0 support

### ISSUE THREAD

**Issue by DJSchaffner** [Godiesc/firefox-gx#165]
Seems like the latest firefox release broke a few things in the design.
Using the latest release (for 125.0) I mainly have issues with some icons gone blank like home, reload, the \<x\> while hovering a tab to close it, etc.

![grafik](https://github.com/Godiesc/firefox-gx/assets/16212271/9e3c78af-60ba-48d5-8e6f-7ea80b1a10fd)

**Comment by Godiesc** [comment]
hi,
those issues maybe are for not pasted the user.js file in your profile folder, be sure to do that.

**Comment by Adjord** [comment]
Hello,
I had the same happen after the update. In my case, simply following the installation process once again fixed all the issues completely.

**Comment by DJSchaffner** [comment]
`user.js` was apparently not the issue, but I reimported the other files and that seems to have fixed it. Not sure what went wrong while updating then.
