### ISSUE TITLE
the address bar font size being smaller and whatsapp extension bugged in firefox gx version 127 in linux mint if that matters

### ISSUE THREAD

**Issue by Midnight0507** [Godiesc/firefox-gx#171]
![whatsapp issue in linux](https://github.com/Godiesc/firefox-gx/assets/110766220/5e59579a-5942-40ac-9ff5-51dd4be78558)

**Comment by Godiesc** [comment]
hi,
the address bar font is smaller horizontal, I do it intentionally, if you want to revert that you can add this code in `chrome/components/ogx_tricks.css` file:

```
/* Urlbar font size */

.urlbar-input-box{
    font-size: inherit !important;
}
```

the issue in whatsapp extension maybe is caused for whatsapp updated its UI, I updated the extension to olve that so be sure to update your extension in about:addons, and open the [whatsapp web page](https://web.whatsapp.com/) one time in a tab to update the page UI.
