### ISSUE TITLE
[Feature Suggestion] The option for Librewolf branding

### ISSUE THREAD

**Issue by KingKrouch** [Godiesc/firefox-gx#174]
Hello! This isn't a bug report per-se, but rather a feature suggestion.

I wonder if there's the chance that an option for Librewolf branding could be added to the Firefox-GX theme, as Librewolf is a fork of Firefox with privacy tweaks out of the box. Just that I found that I had to do some modifications to some of the theme source files and images to change the Firefox branding with the theme.

**Comment by Godiesc** [comment]
hi, I use local images for that and works that way (I think it is not possible to make code to works different for a specific browser), the only solution for you could be to add some code rewriting the code that change that images and that file you keep with every update, and you can point to images in the browser itself and you won't need to put any additional image.
for example you can use the file `ogx_tricks.css` and the code below to make some changes:

```
/* Logo Hamburguer Menu */

:root:not([chromehidden~="toolbar"]) #PanelUI-menu-button .toolbarbutton-badge-stack {
        list-style-image: url("chrome://branding/content/icon32.png") !important;
}

/* Ícono logo-url en paginas seguras de firefox */

#identity-box[pageproxystate="valid"].chromeUI #identity-icon {
    list-style-image: url("chrome://branding/content/icon32.png") !important;
}
```

I don't know where I changed more logos but I think there is no more for Firefox UI.

for the newtab page you should add code at the end of the `userContent.css` :

```
@-moz-document url(chrome://browser/content/browser.xul), url(about:newtab), url(about:home), url(about:privatebrowsing) {
  .logo{
      background: url("chrome://branding/content/icon32.png") no-repeat !important;
  }
```

In future updates of the theme you keep the files used here and all will go well.
