### ISSUE TITLE
Feature : Adding compatibilities whit the GX Mods Extension

### ISSUE THREAD

**Issue by Peperehobbits01** [Godiesc/firefox-gx#175]
Hi, this idea got in my mind for a bit and well I tought that making the extention and the custom css (aka the theme) would be great for a Opera GX but it's Firefox experience thing. Anyway, that's my suggestion, I don't no if it would be hard or not, but I am sure it would be cool :) . Here is a link to the extention in question : [GX-Mods-Extension](https://github.com/noblereign/GX-Mods-Extension)

**Comment by Godiesc** [comment]
I don't understand you, That extension was made for Firefox and should works just fine. **_the custom css (aka the theme)_** for this you have my extension: [GX Them Styles](https://addons.mozilla.org/es/firefox/addon/gx-theme-styles/)

**Comment by Peperehobbits01** [comment]
I am not talking about the theme not matching whit it, it works fine but yeah, I was talking about maybe integrating it in the pack, like having some changes that hapened to it's layout (like the mods manager) when the theme is installed. I don't now if I am clear or if it's even possible, but that's more of I am talking about.

**Comment by Godiesc** [comment]
I don't get it clearly, but make some changes within 'GX Mods Extension' after change the theme or something like that I think isn't possible.
I speak Spanish and that is what I understood.

**Comment by Peperehobbits01** [comment]
Oh, OK. Well, yeah that's was what I was talking about.
