### ISSUE TITLE
Theme isn't saved and the background doesn't appear since v127

### ISSUE THREAD

**Issue by Tintouin** [Godiesc/firefox-gx#177]
I always did my updates correctly without any issue upgrading. But since I use  v127 every time I open firefox, the theme I select is reset and the wallpaper doesn't appear...  It looks like this : 
<img width="1792" alt="Capture d’écran 2024-07-08 à 21 29 48" src="https://github.com/Godiesc/firefox-gx/assets/82973239/f06ae0da-ee78-4014-b672-bf55f8b64168">

**Comment by Godiesc** [comment]
hi, be sure you download the theme from the release section and see the changes notes, starting with Firefox 127 the wallpaper is manage from the 'newtab' preferences, like this:

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/dc7bd24b-28c4-4743-a830-48fd9d2bc081)

and the extension to apply the themes ([GX-Theme-Styles](https://addons.mozilla.org/es/firefox/addon/gx-theme-styles/)) works fine, after a restart for a Firefox update the extension seems to fail 1 time, after another restart should work well.

You should know that the 'GX-Theme-Styles' extension apply the theme every start of the browser and overwrite the theme you have selected in about:addons page. if you want to apply a theme not from the extension pls disable the extension before.

**Comment by Tintouin** [comment]
> and the extension to apply the themes ([GX-Theme-Styles](https://addons.mozilla.org/es/firefox/addon/gx-theme-styles/)) works fine, after a restart for a Firefox update the extension seems to fail 1 time, after another restart should work well.
> 
> You should know that the 'GX-Theme-Styles' extension apply the theme every start of the browser and overwrite the theme you have selected in about:addons page. if you want to apply a theme not from the extension pls disable the extension before.

After trying different things with the various extensions it still doesn't work, the theme fails to load even upon retrying, note that I'm on macOS and it may differ because of that. 

All is set correctly.  

https://github.com/user-attachments/assets/71ac57e0-bbd1-43ec-82d1-e78810fa21ad

and as you can see it's the correct one for a second but it immediately get back to that strange theme

**Comment by Godiesc** [comment]
do you have other extensions that change the Firefox theme? be sure you have on only one, if you use too Firefox-Color that could be the problem.

**Comment by Godiesc** [comment]
@zWolfrost the new way to display the wallpaper was made in the release 127, maybe you don't update the theme in that time, but you can check the [release notes](https://github.com/Godiesc/firefox-gx/releases/tag/v.9.2) to solve that problem.

**Comment by zWolfrost** [comment]
I have already set that config preference to true. After trying the theme on normal Firefox instead of LibreWolf everything works fine (even the background selector shows up), so i assume it is a LibreWolf problem. I understand if fixing this is not a priority though, as making this theme work for every Firefox fork would be really nerve-wracking, so don't worry about it :)

**Comment by Godiesc** [comment]
I guess in a future update of librewolf that feature will be implement it.
