### ISSUE TITLE
Weird tab outline, even with custom tab shapes

### ISSUE THREAD

**Issue by DrWhoFan13** [Godiesc/firefox-gx#178]
Whenever there's a tab open, it's always surrounded by a rectangular red outline in the shape of the Firefox tab. Even in incognito mode & when I use custom tab shapes, it's always there.
![image](https://github.com/Godiesc/firefox-gx/assets/159411967/a9a4b385-90e1-424d-b9b1-51ad2652d665)
![image](https://github.com/Godiesc/firefox-gx/assets/159411967/bd3ef904-30c5-434f-999c-38a3e0e6d87b)

I don't know what's causing it, but it doesn't appear to be tied to any specific version (It appeared in the last version of Firefox GX I downloaded [127] in addition to today's updated release [128], and it appeared in both Firefox beta versions I've used [128 & 129])

**Comment by Godiesc** [comment]
hi, I updated a line of the code in `ogx_tabs-bar.css` to solve it, try to update that file downloading the files from `code->download zip`.

**Comment by DrWhoFan13** [comment]
It's fixed now, thank you!

**Comment by Shankarelius** [comment]
I already replaced all the files with your latest version of Firefox GX. The issue appeared when I was trying to get the left side-bar to show up and messing with getting the configuration right.
