### ISSUE TITLE
selected tabs with tab shapes enabled creates an out of place box

### ISSUE THREAD

**Issue by SugaryGoodness** [Godiesc/firefox-gx#181]
![8vrSGzB](https://github.com/user-attachments/assets/f95de649-aaaf-4705-92ac-cd8113467e40)
![SLqZH15](https://github.com/user-attachments/assets/9a09a490-2f88-457c-82ac-0623601b8167)
![image](https://github.com/user-attachments/assets/944e1b52-5040-4640-9d99-bd88ae16bb61)
![image](https://github.com/user-attachments/assets/83e22eee-a53c-44f7-950c-edd757e042f7)

i'm using the default user.js for tab shapes, and once i turn firefoxgx.tab-shapes to true under about:config, it makes a very distracting and ugly box
this started happening after i updated firefox + firefox-gx
i have tried reinstalling firefox-gx, restarting firefox while testing different tab shapes (happens to them all), and restarting my computer, because why not lol

**Comment by Godiesc** [comment]
hi, that issue was solved, you have this information: https://github.com/Godiesc/firefox-gx/issues/179

**Comment by SugaryGoodness** [comment]
thank you so much for your time! i've only downloaded github things under releases and didn't understand what code -> download zip meant, so totally a user error on my part lol

doing that fixed it!
