### ISSUE TITLE
Translating code and comments from spanish to english.

### ISSUE THREAD

**Issue by Tintouin** [Godiesc/firefox-gx#182]
It is very painful to edit the code with comments and words you can't understand.
I don't want to be mean or anything but I tried editing the code a little bit to add custom icons to extensions and needing to translate some parts of the comments because they are in spanish is a painful process and doesn't help anyone that is not spanish speaking.

I am not a native english speaker and I understand a bunch of spanish but anyway the standard for code is commenting in english.

To fix this it would be very long but pretty easy. You shouldn't add the english translation because it will make the comments overwhelmingly numerous, you should replace with the english translation.

**Comment by Godiesc** [comment]
hi, thanks for the suggestion, in a future I will try to edit the file as I update the code.

**Comment by Tintouin** [comment]
Many thanks friend. I would help if I could. Tell me if you made any update on the README.md so i can update the README.fr.md

**Comment by Godiesc** [comment]
the readme was updated for english and spanish already, I appreciate your help for FR.

**Comment by Godiesc** [comment]
I translated the comments, I'm not sure if its the best translation but I tried it.
