### ISSUE TITLE
Colors Problem

### ISSUE THREAD

**Issue by MatiVillabrille** [Godiesc/firefox-gx#188]
I think it is easy to solve, however I would rather need you to tell me how, the colors of the logo and the central search bar cannot be changed with the gx theme extension, also the letters under the shortcuts cannot be changed either. I don't know if they can be removed or changed color in any other way. In the case of the logo, I reviewed the .svg and verified that it is black, so I should change the corresponding line of code for it. The issue is that I don't know where it is located.
![Uploading imagen_2024-08-01_140854648.png…]()

**Comment by Godiesc** [comment]
hi, 
First of all the the image you shared is inaccessible.
I know that the gx theme extension doesn't change all the font colors and that's because I tried to keep it simple without too many options that might confuse the user. For the logo and wordmark color in the NewTab page you can change it and you have this info in the github page, the accent color give that them the color.

![imagen](https://github.com/user-attachments/assets/e252c5f2-4f2e-451e-a3ae-2135845d72eb)

**Comment by OXMoonFoxXO** [comment]
I think he mean buttons such as back, forward and reload, because I am facing the same problem and it's kinda triggering me. Here is a video of me trying to change the color of these svgs https://imgur.com/a/CueiTXn

**Comment by Godiesc** [comment]
hi, that problem is caused for you didn't paste the `user.js` file into your profile folder to active the preferences in about:config automatically, all that preferences are necessary to the right work of the theme. If you prefer to do it manually be sure to active all the preferences of the user.js file, the one you have problem is this:

**Comment by Godiesc** [comment]
and I saw in your video you have a problem with the line under the tabs, maybe you download the theme from the wrong place, for 'release version' of Firefox you have to download the theme from the '[Releases](https://github.com/Godiesc/firefox-gx/releases)' section.

**Comment by MatiVillabrille** [comment]
> hi, First of all the the image you shared is inaccessible. I know that the gx theme extension doesn't change all the font colors and that's because I tried to keep it simple without too many options that might confuse the user. For the logo and wordmark color in the NewTab page you can change it and you have this info in the github page, the accent color give that them the color.
> 
> ![imagen](https://private-user-images.githubusercontent.com/22057609/354331485-e252c5f2-4f2e-451e-a3ae-2135845d72eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MTY5NjcsIm5iZiI6MTcyMjcxNjY2NywicGF0aCI6Ii8yMjA1NzYwOS8zNTQzMzE0ODUtZTI1MmM1ZjItNGYyZS00NTFlLWEzYWUtMjEzNTg0NWQ3MmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDIwMjQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5Mzc2YzFlOTg0NjI3NTQzYWVhNGI2MzY4YWZjNjY2OWUyYTZhNGI5YzQ1M2UyOWE0YzJkMGU3OTJjZTYwYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rgAJ_2amum8UwaO5kvoZgukGAQx-uLzFu_s9kaHT89w)

I'm sorry about the issue with the image. I hope the next one is visible. The parts highlighted in yellow are what I would like to change: the logo, the red line in the search bar, the color each shortcut changes to, and the text, which, as you can see, is invisible with the background I applied.

I understand that you might not intend to add customization options to keep things simple for users. While I don't necessarily agree with this approach, as some people might appreciate the simplicity, there's nothing more to add on that front. In that case, could you please let me know where in the code I can modify the colors for the parts I've marked? It doesn't seem to be in the lines you mentioned.
![Sin título](https://github.com/user-attachments/assets/cf3eefe8-bbc2-480f-814a-2824487610df)

**Comment by Godiesc** [comment]
to change the color of Firefox logo, wordmark and line in the search-bar you can do it changing the wallpaper, they have some preset color, I guess you want the last one:

https://github.com/user-attachments/assets/00950f1c-df18-47ff-ba7f-b71266e14365

the black label color on the pinned sites maybe is a issue caused for your system theme that maybe is 'light', to make the when content adapted to dark themes you should that in the preferences of Firefox, in this part: 

![imagen](https://github.com/user-attachments/assets/88326ea8-be16-43ba-a425-2ec8583d6f39)

**Comment by MatiVillabrille** [comment]
> hi, First of all the the image you shared is inaccessible. I know that the gx theme extension doesn't change all the font colors and that's because I tried to keep it simple without too many options that might confuse the user. For the logo and wordmark color in the NewTab page you can change it and you have this info in the github page, the accent color give that them the color.
> 
> ![imagen](https://private-user-images.githubusercontent.com/22057609/354331485-e252c5f2-4f2e-451e-a3ae-2135845d72eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MTY5NjcsIm5iZiI6MTcyMjcxNjY2NywicGF0aCI6Ii8yMjA1NzYwOS8zNTQzMzE0ODUtZTI1MmM1ZjItNGYyZS00NTFlLWEzYWUtMjEzNTg0NWQ3MmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDIwMjQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5Mzc2YzFlOTg0NjI3NTQzYWVhNGI2MzY4YWZjNjY2OWUyYTZhNGI5YzQ1M2UyOWE0YzJkMGU3OTJjZTYwYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rgAJ_2amum8UwaO5kvoZgukGAQx-uLzFu_s9kaHT89w)

I'm sorry about the issue with the image. I hope the next one is visible. The parts highlighted in yellow are what I would like to change: the logo, the red line in the search bar, the color each shortcut changes to, and the text, which, as you can see, is invisible with the background I applied.

I understand that you might not intend to add customization options to keep things simple for users. While I don't necessarily agree with this approach, as some people might appreciate the simplicity, there's nothing more to add on that front. In that case, could you please let me know where in the code I can modify the colors for the parts I've marked? It doesn't seem to be in the lines you mentioned.
![Sin título](https://github.com/user-attachments/assets/cf3eefe8-bbc2-480f-814a-2824487610df)
i see that the problem i'ts other in that case, if i press the button of the video i only see the default wallpapers of mozilla
![Sin título](https://github.com/user-attachments/assets/f0d81bf0-567e-45c6-9cc7-01f9f7c336f4)
Maybe solve this problem can solve the dark mode problems in the shortcut, because i have the dark mode activated in the preferences

**Comment by Godiesc** [comment]
seems you have active the next version of the 'wallpaper' feature, and the theme only is compatible with the first one: 

![imagen](https://github.com/user-attachments/assets/531db62b-40b6-435d-8eb4-8a02e12a6e60)

**Comment by MatiVillabrille** [comment]
Problem solved, thank you

**Comment by MatiVillabrille** [comment]
I found another problem related to those two settings. Every time I close Firefox and reopen it, the configs `browser.newtabpage.activity-stream.newtabWallpapers.v2.enabled` and `browser.newtabpage.activity-stream.newtabWallpapers.highlightDismissed` switch back to `true` again. It might be an issue with my extensions, but I want to make sure there's no file in the theme that could be modifying it.

**Comment by Godiesc** [comment]
hi,
you can see info here in [this new reported issue](https://github.com/Godiesc/firefox-gx/issues/190) that change that preferences automatically cause by Firefox `Studies`, you can solved pasting the new `user.js` file or changing that studio status.

**Comment by MatiVillabrille** [comment]
The new user.js didn't solve the problem at first, but disabling v2 in about:studies did. Thanks again
