### ISSUE TITLE
Wallpapers don't save/ work

### ISSUE THREAD

**Issue by Niktris** [Godiesc/firefox-gx#189]
When opening a new tab, the wallpaper is set back to it's preset equivalent. When I then try to reselect the wallpaper I added using the "newtab" folder inside the "chrome" folder it will change to the correct one but as soon as I go out of the "Photographs" option of the Wallpaper selection inside the browser it changes back to the preset. also wallpaper number 3 is not in the "Photographs" but in the "abstract" option of the wallpaper selection. also when opening one of the three wallpaper options inside the wallpaper selection the folder opens on top of the selection menu.

I have tried to make a video showing the problem. I hope this helps. 

https://github.com/user-attachments/assets/ffa24c9e-a652-444c-868b-b9d69b038421

**Comment by Godiesc** [comment]
hi,
thanks for the report, Firefox Beta is using a second version of wallpapers by default and the theme isn't compatible yet with that, I don't know if could be compatible in a future, I hope I could fix it, for now you can disable the new version turning false the next preference in `about:config` page: 

`browser.newtabpage.activity-stream.newtabWallpapers.v2.enabled`

**Comment by ItzELECTR0** [comment]
> for now you can disable the new version turning false the next preference in about:config page: browser.newtabpage.activity-stream.newtabWallpapers.v2.enabled

THAT IS A LIFE SAVER! I was going through all of the code trying to work it out myself but this just works! Thanks!

**Comment by Godiesc** [comment]
I updated the files to solve this issue, you can download the theme from `code -> download zip` to get the latest files, don't forget to paste into your Firefox profile directory the `user.js` file too.

**Comment by ItzELECTR0** [comment]
The wallpaper menu button is gone after replacing the files. How does one change wallpapers now?

**Comment by ItzELECTR0** [comment]
> The wallpaper menu button is gone after replacing the files. How does one change wallpapers now?

Well it's apparently still there, just invisible. Took me a couple of clicks to find it.

**Comment by Godiesc** [comment]
solved with the latest theme release.
