### ISSUE TITLE
Different Wallpaper Issue

### ISSUE THREAD

**Issue by KingOreoTheThird** [Godiesc/firefox-gx#190]
Ok so I will try to describe the issue as it's different from the other guys issue.

I start firefox and my wallpaper I chose last time before I closed the browser is gone. Then I change it and it works if I make a new tab the wall paper vanishes and is back to normal.

If you need videos ill send it

**Comment by Godiesc** [comment]
I assume you tried the solution [to the other issue](https://github.com/Godiesc/firefox-gx/issues/189) and it didn't work for you? If so, then it is necessary for you to show that problem in some way.

**Comment by WontresGit** [comment]
I have the same issue. I did try to change the `about:config` in `browser.newtabpage.activity-stream.newtabWallpapers.v2.enabled` to false, and that works. However, Firefox resets the value to true every time I restart Firefox.

**Comment by Godiesc** [comment]
hi, I updated too the user.js file to disable that preference for other user than maybe have the same issue, you can paste again the new `user.js` file into your `profile folder`.

**Comment by KingOreoTheThird** [comment]
THANKJ YOU THIS WORKED

**Comment by Peperehobbits01** [comment]
It can not be turned off in studies anymore. It's is now studie finish. Guess I will wait for the fix then :wink:

**Comment by Godiesc** [comment]
I updated the files to solve this issue, you can download the theme from `code -> download zip` to get the latest files, don't forget to paste into your Firefox profile directory the `user.js` file too.

**Comment by Peperehobbits01** [comment]
Thanks, it fix it!
