### ISSUE TITLE
[LibreWolf] Wallpaper selector does not show any content

### ISSUE THREAD

**Issue by SamuelLMT** [Godiesc/firefox-gx#191]
<img width="960" alt="CopyQ gHzTKE" src="https://github.com/user-attachments/assets/88bcf4db-a35f-4466-a6ca-c952f9a8ffd7">

The wallpaper selector shows no wallpaper even after a fresh install of the files. It works on Firefox, but I use LibreWolf.

Is there a way to fix this issue or to edit the newtab wallpaper without the selector? I don't plan on changing the browser.

**Comment by Godiesc** [comment]
hi,
maybe if you download a previous version of the theme you can solve it, for example you can download the [v.125-126](https://github.com/Godiesc/firefox-gx/releases/tag/v.9.1) and copy the files `ogx_UC-newtabpage.css` and `ogx_root-personal.css` and paste and replace the files in your actual theme files, the wallpaper name was `wallpaper-dark.png` if I'm not wrong, you can put a image with that name into `newtab` folder.

**Comment by SamuelLMT** [comment]
Thank you. Don't know what LibreWolf got rid of that made it not work. Fixed now.
