### ISSUE TITLE
KeePassXC and Violentmonkey Icons on sidebar

### ISSUE THREAD

**Issue by ghost** [Godiesc/firefox-gx#192]
Los iconos de KPXC y Violentmonkey no se apegan al tema, sé que no todas las extensiones están diseñadas para esto, pero quería saber si es posible que agregues sus iconos o quizá comentar como hacer esto manualmente para no molestarte. Gracias!

![image](https://github.com/user-attachments/assets/c330f65c-1fe4-4ca4-b5ce-1b0d3b487507)

**Comment by Godiesc** [comment]
hi, perdón por la respuesta tardía, muchas veces GitHub no me notifica por correo, muy raro.
En discusiones agregué, hace un tiempo, los pasos para hacer eso, no se si te resulte fácil o difícil, está descrito aquí: https://github.com/Godiesc/firefox-gx/discussions/157
