### ISSUE TITLE
[Bug & Enhancement] Firefox Home Wallpaper + Context Menu Icons

### ISSUE THREAD

**Issue by GrPK** [Godiesc/firefox-gx#195]
Hello! I've read the latest issues posted here but idk if they are the same is mine...

Nonetheless, the bug is the fact that when I start Firefox first time, it takes some seconds to load the wallpaper... Is there any other way to hard-code what wallpaper I want? In the previous version there was a way to do it (the first few seconds of the video)

Secondly, is there any way to add a Icon next to Ask ChatGPT menu in context window? It is the new Firefox Labs feature and I really love it to use. Also, if you change the GPT (Claude, Gemini), the context text is changing accordingly to the GPT (this is case you don't use the beta version). I tried to edit your icons.css file but unfortunately it dosen't work.

Lastly, is there any way to change the icon of an extension? The Ask GPT options works amazing with sidebar extension from mozilla but the icon is black

You can see the last 2 issues on the second part of the video.

Thanks and waiting for your feedback!

https://github.com/user-attachments/assets/1f2cdc4f-ce2a-4ace-a2c0-a5daab9b4f89

**Comment by Godiesc** [comment]
hi,
1.- for the inconvenient of the wallpaper at the start of the browser (I guess you are using the latest code of the repository) and you  are using the version 2 of that Firefox Feature maybe in a future Firefox itself improve that performance, did you test it without Firefox-GX theme and you saw if that delay persist?
Maybe a way to improve is don't use the set of wallpapers and set only one wallpaper right in the 'body' element.

2.- For default I will try to add that new icons in those new elements (IA) of contextual menu, 
3.- A lot of extensions has icons that work only on a specific background, Your other extensions have icons that work on light or dark backgrounds. for [Side view](https://addons.mozilla.org/es/firefox/addon/side-view/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) extension, I guess that is the one you are using I will try to give it other icon.

**Comment by GrPK** [comment]
Hey, regarding 2, thanks, for 3, yes that's the extension, but for 1:

I didn't understand how can I set only one wallpaper? Should I edit one of the css or? Sorry for my miss-understanding

**Comment by Godiesc** [comment]
for the background set with one image you should add this code to the end of `ogx_UC-newtabpage.css`:

```
@-moz-document url(chrome://browser/content/browser.xul), url(about:newtab), url(about:home), url(about:privatebrowsing) {
    body{ 
        background: url("../newtab/wallpaper-dark1.png") !important;
        background-size: cover !important;
        --general-color: var(--fuchsia) !important;
    }
}
```

and you should clic this option too:

![imagen](https://github.com/user-attachments/assets/8bd0b27b-1578-478b-9ebd-a5b0f4672d6e)

**Comment by Godiesc** [comment]
I updated the code in the main branch to add the icons you request, I don't know if issues will appear in Firefox stable if you test it but in September 3 that Firefox v.130 arrive won't have any problem.

**Comment by GrPK** [comment]
Hi,
It worked amazingly, thanks for your dedication!
Just one last question. I've updated with your code:
![image](https://github.com/user-attachments/assets/4129c20c-3dc3-4efb-9634-e456bad04aca)


How can I make that line purple as well? It changes color after a few seconds, but I want to hard-code it like I did with wallpaper2 and purple color

**Comment by Godiesc** [comment]
Maybe just delete that line --general-color an use de --general-color in ogx_root-personal.css

**Comment by GrPK** [comment]
![image](https://github.com/user-attachments/assets/b22a740a-3088-44b1-9ae8-ba809d74d68a)


Yeap, it worked! 
Thanks again for your help!
