### ISSUE TITLE
An Opera GX mod for Zen Browser

### ISSUE THREAD

**Issue by KjalaNIX** [Godiesc/firefox-gx#196]
Sorry to post an issue that might not be as relevant but it would be nice if there was an opera GX mod for the newest Firefox-based browser Zen. Then have it submitted in zen-browser.app/themes . It would be installable in one click. Thank you in advance.

**Comment by Godiesc** [comment]
Hi, I don't know how zen works and it takes a lot of time and effort to achieve compatibility with another browser, I don't know if it can happen in the future.
