### ISSUE TITLE
Classic Sound Icon not working properly on Firefox Beta

### ISSUE THREAD

**Issue by DrWhoFan13** [Godiesc/firefox-gx#200]
![image](https://github.com/user-attachments/assets/c5aa144a-09e2-4bb2-894b-e3d4e20eddac)

Self-explanatory, as seen above, the Classic Sound Icon looks weird on the latest Firefox Beta version for Windows. I don't understand what, exactly, is causing this problem.

**Comment by Godiesc** [comment]
hi, thanks for the bug report, In this moment Firefox is changing its UI for incoming sidebar+verticalTabs+groupTabs and a lot of code will need change, for this issue in particular Did you apply the extra 'Classic-Sound-icon'? if yes, I will take a look to solve it but maybe it will take a long time than a little while.

**Comment by DrWhoFan13** [comment]
> Did you apply the extra 'Classic-Sound-icon'?

I did, yes.

**Comment by GrPK** [comment]
+1 Can confirm the same bug

**Comment by Godiesc** [comment]
I updated the files to solve this issue, and there is a new way to apply this configuration, the information was updated in the '[Extras](https://github.com/Godiesc/firefox-gx/tree/main/Extras/Classic-Sound-icon)' section.
If you find any issue please report it.

**Comment by DrWhoFan13** [comment]
Works for me, thank you _so_ much.

**Comment by Godiesc** [comment]
Solved in the latest theme release, thanks for reporting the issue. 💙
