### ISSUE TITLE
Weird Space under the Firefox logo

### ISSUE THREAD

**Issue by Nesquirt** [Godiesc/firefox-gx#201]
HI,
yesterday i updated to the latest version and i found that trying sidebar, if u disable it keep the space under the firefox logo.
![immagine](https://github.com/user-attachments/assets/4bb68cbc-631e-4274-827d-afc64c9afa5d)

**Comment by Godiesc** [comment]
hi,
do you mean this sidebar, I just tested it and seems right:

https://github.com/user-attachments/assets/622b87c3-bdc7-4031-90ca-0185e5c042fb

Maybe do you apply the 'Extra' in a wrong way?

**Comment by Godiesc** [comment]
@Nesquirt tested again and the problem seems to be this:

![imagen](https://github.com/user-attachments/assets/701e2bde-e6c4-4cd4-a156-6672bddb808e)

active again that sidebar and change that option and that will solve the issue.

**Comment by Nesquirt** [comment]
![immagine](https://github.com/user-attachments/assets/de336980-40d1-40e2-998d-b71d22d18934)
did what u told me, but now i have this and i cant hide :(

**Comment by Godiesc** [comment]
now that you changed that you can remove that sidebar with the preference in about:config that you have turned 'true' before and toggle it.

`sidebar.revamp` - `false`

**Comment by Nesquirt** [comment]
Should try tomorrow thanks anyway!
