### ISSUE TITLE
Firefox logo and search bar in new tab are a different color from the one I picked

### ISSUE THREAD

**Issue by ToxictheJimmy** [Godiesc/firefox-gx#203]
Problem is self-explanatory, I fixed it somehow before I updated to the most recent version of firefox-gx and the solution is most likely the same, but I unfortunately don't remember how I fixed it and forgot to save the solution when I changed to the newest version.

![Screenshotnewtab](https://github.com/user-attachments/assets/b175fb1f-d63e-4a8c-bba4-3f57877e6b8e)

**Comment by Godiesc** [comment]
hi,
the accent color is different for each wallpaper, and you have all this rules in `ogx_root-personal.css` file:

![imagen](https://github.com/user-attachments/assets/c6e7ff53-9d06-4343-8105-5bc5e218e885)

**Comment by ToxictheJimmy** [comment]
Yeah, I think my problem was that I changed the main-image but changing the general-color variable was not working. I did it by changing the picture's name to one of the "wallpaper-dark" options, and changing the hex code of the color I picked (as it was not the kind of green I wanted). Thank you so much for the response! Have a good weekend!
