### ISSUE TITLE
[Request] A load progress bar beneath the urlbar.

### ISSUE THREAD

**Issue by clifford269** [Godiesc/firefox-gx#204]
Is that possible?

**Comment by Godiesc** [comment]
hi, I didn't see any theme do that, maybe if you know one I could look the code to see if I can implemented, for now there are two options to simulate that but only into the tab, you can test them adding the code one by one using the `ogx_trick.css` file.
- [tab_loading_progress_throbber](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/tab_loading_progress_throbber.css)
- [tab_loading_progress_bar](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/tab_loading_progress_bar.css)

**Comment by clifford269** [comment]
Sure thing! Here is one. It creates progress bars on top of webpages
https://github.com/luben/load-progress-bar/
Store: https://addons.mozilla.org/en-GB/firefox/addon/load-progress-bar/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

**Comment by Godiesc** [comment]
well if you have that extension you don't need to do it with css, that in my knowledge its impossible just with css, the extension use javascript.

**Comment by clifford269** [comment]
Well, can't we use JS?

**Comment by Godiesc** [comment]
you can use JS but this theme use only CSS cause I don't want to make the browser vulnerable, but if you want to use js you can do it (but I won't help you with the code) with the next info: https://garywill.github.io/enblog/post/ucjs/

**Comment by clifford269** [comment]
I am quite familiar with JS- https://github.com/clifford269/FrutigerFX
Don't want it vulnerable? Hah!
