### ISSUE TITLE
Adaptive tab bar color

### ISSUE THREAD

**Issue by duckaleuze** [Godiesc/firefox-gx#205]
could you make an alternative userchrome or something to make it compatible with [Adaptive tab bar color](https://addons.mozilla.org/en-US/firefox/addon/adaptive-tab-bar-colour/)? it would be nice!

**Comment by Godiesc** [comment]
hi,
It seems like it works, it change the colors of tabs-bar and toolbar, maybe the gradient line could be a problem cause that is taken from the theme.

https://github.com/user-attachments/assets/51fe3f74-f7ab-4327-8e87-11dfad189389

**Comment by Godiesc** [comment]
I tested a little and this code could do a good work, you can add it in the `ogx_tricks.css` file:

```
/* New Accent color */

:root {
  --my-new-accent-color: lch(from var(--lwt-frame) calc(l + 40) c h) !important;
  --general-color: var(--my-new-accent-color) !important;
}

/* Reset global variables */

:root,
:root[lwtheme],
:root:not([lwtheme]){
  --lwt-frame: var(--arrowpanel-background) !important;
  --lwt-selected-tab-background-color: var(--lwt-accent-color) !important;
}

/* We set the new color directly to the tabs-bar & menu-bar */

#TabsToolbar, #toolbar-menubar{
  background-color: var(--lwt-frame) !important;
}
```

**Comment by duckaleuze** [comment]
thank you :D looks awesome

**Comment by Godiesc** [comment]
This code was added to '[Tricks](https://github.com/Godiesc/firefox-gx/tree/main/Tricks#compatibility-with-adaptive-tab-bar-color-extension)' section for anyone who likes that extension.
