### ISSUE TITLE
tabs are surrounded by red line that keeps them from merging with the rest of the browser

### ISSUE THREAD

**Issue by anttiuauau** [Godiesc/firefox-gx#207]
Hey guys, I'm having some problems with the tabs. So, as you see, the tabs are surrounded by red line that keeps them from merging with the rest of the browser while open. I hope someone could help me. I mean, it is not a big deal but it is kind of a bummer. 
![aaaaaaaaaaa](https://github.com/user-attachments/assets/4fe74c1f-a689-4cc4-ac56-8be5fdbdd15f)

P.D.: I love this theme, i really love it, so thank you guys for making this.

**Comment by Godiesc** [comment]
hi, 
That issue was solved since previous version, just download the latest release version of the theme.
