### ISSUE TITLE
Sidebar not working, shows no content (Windows 11 24H2, Firefox 131.0.3, Firefox GX 131.0)

### ISSUE THREAD

**Issue by NerdyWanKenobi** [Godiesc/firefox-gx#208]
![image](https://github.com/user-attachments/assets/e3d9f760-c653-45c2-b54b-87ea65e21565)
Firefox just automatically updated to the latest version, and now the sidebar is just gray and does not show any of my bookmarks or pinned icons.  I updated Firefox GX from 130.0, which I was initially on, to 131.0 (pictured here), which seems to be the latest version as of posting this, and the problem persisted.  I cannot access my bookmarks or anything else pinned to the sidebar.  Is a fix coming for this?

**Comment by Godiesc** [comment]
hi,
The 'Left-sidebar' use the bookmarks-bar so be sure you set it in 'Always Show'.
