### ISSUE TITLE
Can't change the background when opening a new tab

### ISSUE THREAD

**Issue by AstralDice** [Godiesc/firefox-gx#209]
As you might now that if you open a new tab, you get a new tab with the Firefox GX (calling it fgx from now on) logo, the Google searchbar, important links and stuff. I wanted to change the background, but if I click on a background image I wanna use and then close the selection "screen", it turns to something completely different (see images down below)

That's the normal new tab stuff
![grafik](https://github.com/user-attachments/assets/2888de96-cfab-45cf-8789-919d62765ec3)

That's me selecting my wanted new background (you might alr be able to see from the menu on the top right that it'll change to something completely different)
![grafik](https://github.com/user-attachments/assets/b4bfa481-d524-481d-81a3-e36be456d147)

That's me being irritated cause I don't know why it turned out like that lol
![grafik](https://github.com/user-attachments/assets/65860e3d-6a14-4a15-a5c3-0b2e524fb4c7)

Whenever I change it to something else, all images that are available are busted and I don't know why. Btw can there be an update with whom one can change the background to the one you desire? thx alot in advance!

**Comment by Godiesc** [comment]
hi,
when you use a CSS theme like this you should update (from time to time) to latest release version of the theme, and when you see a lot of issues like you experiment you should just see the '[Releases](https://github.com/Godiesc/firefox-gx/releases)' section and download the updated files.
