### ISSUE TITLE
Play-Pause extension is not installing

### ISSUE THREAD

**Issue by MauiFizz** [Godiesc/firefox-gx#210]
I tried installing the play-pause extension from the Extras section. When I add @play-pause.xpi file from Extensions and Themes, it says that the file appears to be corrupt.
![Screenshot (160)](https://github.com/user-attachments/assets/523cac11-5df9-4255-90ef-bd936dde9670)

**Comment by Godiesc** [comment]
hi,
in your profile folder there is a folder called 'extensions', copy and paste the extension into that folder and restart the browser.
