### ISSUE TITLE
[Question] Sidebar opening is abrupt, make it float above page?

### ISSUE THREAD

**Issue by Felina-Lain** [Godiesc/firefox-gx#212]
Hello, thanks for the amazing work, making firefox better!
I got a question (though it might be better asked on the extensions pages, but I'll ask it here first, in case)
The extensions you advised to put in the sidebar to achieve the same effect as in GX, open by creating a new space next to the bar.

That new space when appearing, will "shove" the page that's currently opened, to the side, rather abruptly
Is there a way to mitigate this found here that I missed, or would it be better to ask each extension devs?

thanks again, hope you have a nice day/night

**Comment by Godiesc** [comment]
hi,
Sadly Firefox Sidebar just work pushing the web content and any developer can't make it smoother or floating, maybe with some css code you can add a transition (I'm nor sure how could work), or make that sidebar bigger when you 'hover' on it, and make it smaller when you not 'hover' on it.
Other limitation of Firefox-Sidebar is that the content is lost when you close the sidebar, This Firefox feature isn't so good like Opera.

**Comment by Felina-Lain** [comment]
> hi, Sadly Firefox Sidebar just work pushing the web content and any developer can't make it smoother or floating, maybe with some css code you can add a transition (I'm nor sure how could work), or make that sidebar bigger when you 'hover' on it, and make it smaller when you not 'hover' on it. Other limitation of Firefox-Sidebar is that the content is lost when you close the sidebar, This Firefox feature isn't so good like Opera.

Ah gotcha. Thanks for answer and explaining, I'll just get used to it after a while I guess XD
