### ISSUE TITLE
change search bar color

### ISSUE THREAD

**Issue by sasik007** [Godiesc/firefox-gx#214]
![Screenshot_20241027-120403](https://github.com/user-attachments/assets/246996f6-173f-46eb-a6f0-f12957884a5c)

hello game can i change the color of this element? i would like to change the color of the url bar because now it is too blurry and not legible

**Comment by Godiesc** [comment]
hi,
the urlbar is blurry? mmm, I don't understand that, but cause design the urlbar is the same color od the toolbar, or do you mean the url font color?

**Comment by sasik007** [comment]
maybe I wrote it wrong but how do I change the color of the url bar and toolbar? I would like to change the color a bit

**Comment by Godiesc** [comment]
you can use another theme in about:adons, or you can use the extension I made to change the colors: [GX_theme-styles](https://addons.mozilla.org/firefox/addon/gx-theme-styles/):

![imagen](https://github.com/user-attachments/assets/33cfaa01-e52c-4fba-b7fc-b18a8ecf0896)

if you mean give a diferent color to the urlbar and other color to the toolbar so you will need a css code.

**Comment by sasik007** [comment]
yes I use this but it changes everything at once, how can I change only the place where the address is entered?

**Comment by Godiesc** [comment]
you can use the chrome/components/tricks.css file to ad the code for your personal preferences and add this:

```
:root,
:root[lwtheme],
:root:not([lwtheme]){
  --toolbar-field-background-color: red !important;   /* toolbar_field */
}
```

**Comment by sasik007** [comment]
jestws great thank you very much, I will have more such questions because I would like to adapt it a bit to myself, can I ask?

**Comment by Godiesc** [comment]
keep in ind this theme is inspired in OperaGX and was designed with that purpose, if you want a big change maybe will be impossible for me to help you, if is a small changes won't be a problem.

**Comment by sasik007** [comment]
can the shape of this fence be changed so the corners are round?

**Comment by Godiesc** [comment]
fence? do you mean the corners of the urlbar? you can add this other variable after the first one:

```
:root,
:root[lwtheme],
:root:not([lwtheme]){
--toolbar-field-background-color: red !important;   /* toolbar_field */
--border-radius-urlbar-personal: 20px !important; 
}
```

**Comment by sasik007** [comment]
ok and please how to change the background in firefox settings?

**Comment by Godiesc** [comment]
the background color or the image? in the main page of this theme you have the info, the wallpaper image is took from `chrome/newtab/wallpaper-dark1.png`

**Comment by sasik007** [comment]
![Zrzut ekranu (3)](https://github.com/user-attachments/assets/22c5c7aa-8ff4-4eee-9441-bae120ed3d9a)
here.

**Comment by Godiesc** [comment]
yeah, I gave you the answer, the image with the name `wallpaper-dark1.png` or `wallpaper-light.png1` is taken to use it in that page. If you changed the image with that name you should restart your browser to see the change.

**Comment by sasik007** [comment]
it works, thank you for your help, it would be nice to have all the components in this folder one by one so that you could change the colors of everything.P.S. did you do something with the translator because something is not showing up on the bar.

**Comment by Godiesc** [comment]
the translation button seems right:

![imagen](https://github.com/user-attachments/assets/3c8be38d-d354-4592-b38b-6f2eed3e63e1)

and after the page is translated the icon change to this:
 
![imagen](https://github.com/user-attachments/assets/f38ce15e-b489-4a8e-877b-187385bb5b56)

**Comment by sasik007** [comment]
I must have messed something up because it doesn't work for me, I don't even have that icon,

**Comment by Godiesc** [comment]
for example in my case I use the 'Simple translate' extension so that button don't show, and if I want tor use the Firefox translation I use the button in the hamburger menu.

**Comment by sasik007** [comment]
is it possible to somehow save all my settings?

**Comment by sasik007** [comment]
![IMG_20241027_190807660](https://github.com/user-attachments/assets/bf780a15-f208-47ce-8eec-f8dc858d67c1)
and one more question how to change the color of this frame

**Comment by Godiesc** [comment]
> is it possible to somehow save all my settings?

Firefox settings I guess sync with an account, for this theme the` ogx_tricks.css` file with your personal code just kept it and use it when you need to update your theme.

> and one more question how to change the color of this frame

you can add this variable after the other variables:

`--toolbar-field-focus-background-color: red !important;      /* toolbar_field_focus */`

**Comment by sasik007** [comment]
thank you, is there a collection of these commands somewhere so that you know what to change for a given element? where do you know all this?

**Comment by sasik007** [comment]
so could you tell me how to change the font color in this box from black to white?

**Comment by Godiesc** [comment]
in the `chrome/components/ogx_root.css` I used a lot of that variables to change general colors, not all but a lot.
You can use the [developer console](https://firefox-source-docs.mozilla.org/devtools-user/browser_toolbox/index.html) to inspect the elements you want to change and is the way to learn the css and the variables, and you can change the style to what you want.

**Comment by sasik007** [comment]
so could you tell me how to change the font color in this box from black to white?

> > is it possible to somehow save all my settings?
> 
> Firefox settings I guess sync with an account, for this theme the` ogx_tricks.css` file with your personal code just kept it and use it when you need to update your theme.
> 
> > and one more question how to change the color of this frame
> 
> you can add this variable after the other variables:
> 
> `--toolbar-field-focus-background-color: red !important; /* toolbar_field_focus */`

after this change the whole background changes and I was talking about the frame itself

**Comment by sasik007** [comment]
![IMG_20241028_205429350_HDR](https://github.com/user-attachments/assets/fa259d88-65ef-4b6b-b56f-59d2ecdd3661)
I'm trying I'm playing with it but I don't know how to search for elements like the search bar etc.

**Comment by Godiesc** [comment]
> after this change the whole background changes and I was talking about the frame itself

The theme don't have any border on the urlbar [open] maybe you are using other code that change it. but with the next code you can overwrite, I guess:

![imagen](https://github.com/user-attachments/assets/d9b0f56d-9d08-432c-a931-de17e3b2acbd)

```
#urlbar[open] #urlbar-background {
      border-color: red !important;
}
```

and for the font color, in dark themes should be white color by defaul, I don't know if you are making other changes but this variable should work:

`--toolbar-field-focus-color: red !important;                          /* toolbar_field_text_focus */`

![imagen](https://github.com/user-attachments/assets/51e6b91e-c281-4eee-b768-af51779cd8bb)

**Comment by sasik007** [comment]
thanks for the screenshots thanks to that I know where to change it, but why after entering the color red I have yellow? can't I change to another color? and how to save the changes?

**Comment by Godiesc** [comment]
I said you that the file `ogx_tricks.css` is for your personal code.
And the color should apply without problems, I saw in your Screenshot that you have a white line in top of your web content that this theme doesn't have, if you are adding code in other way or I don't know all the thing you are changing but is difficult for me to help you.
