### ISSUE TITLE
issue: Search bar position glitch

### ISSUE THREAD

**Issue by ItzELECTR0** [Godiesc/firefox-gx#217]
I'd like to start by mentioning that this happens in Firefox Developer Edition (And probably Nightly) only.
Issue appears only in 133.0b1 through 133.0b3 and NOT in 132.0

Not entirely sure if it's because of the theme, but I've tried disabling all extensions and the issue persists so I decided to make this issue.
When firefox starts everything is normal, but when using the search bar things start glitching out:

First it positions itself at the top of the screen:
<img src=https://github.com/user-attachments/assets/54019d14-f43a-4b13-8ff6-d5ee59009e06 alt-text=first width=800></img>

Then after that when it isn't being used, it places itself in the center:
<img src=https://github.com/user-attachments/assets/cfd7bbbe-badb-462b-afe4-477e8de3d619 alt-text=first width=200></img>

And it becomes transparent when not interacted with:
<img src=https://github.com/user-attachments/assets/bfdecf56-83f5-4bac-a041-aa2533d83797 alt-text=first width=200></img>

Also has a highlight on hover:
<img src=https://github.com/user-attachments/assets/9d74059f-928b-4970-9984-4ff0158126b6 alt-text=first width=200></img>

It doesn't affect using the browser, and there aren't other glitches, but it's very annoying to have it constantly in the center.
It also covers things on web pages which is frustrating to say the least.
I hope pointing it out helps towards fixing it sooner, good luck!

**Comment by Godiesc** [comment]
hi,
I'm using 'Developer edition' and I didn't see that issue maybe you have some personal code in your `ogx_tricks.css` or do you added other code in some way? I didn't experiment any similar of this problem.

![imagen](https://github.com/user-attachments/assets/27834db1-7374-45f3-a412-2517eb1f4efc)

**Comment by ItzELECTR0** [comment]
Discovered the issue, it was a CSS file from MrOtherGuy's [firefox-csshacks](https://github.com/MrOtherGuy/firefox-csshacks)
I use quite a few, but I've narrowed it down to the cause: [this one](https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/compact_urlbar_megabar.css)

Not importing the file fixed the issue, but I'm also going to look for a way to make it compatible again.
