### ISSUE TITLE
Firefox GX always changes theme back to Fuchsia whereas I "deleted" any trace of fuchsia to get Firefox to turn blue or grey

### ISSUE THREAD

**Issue by AstralDice** [Godiesc/firefox-gx#219]
I've been trying to change my theme from fuchsia to blue (or grey, still trying to figure out which one I like best, cause I got a gd background now lol I love nullscapes), but even after deleting the fuchsia theme and changing my personal root on the components thingy, it still goes back to fuchsia and I don't know what I'm doing wrong...

Edit:
Call me Usain Bolt, I almost immediately fixed it by deleting GX Theme Styles lol

**Comment by Godiesc** [comment]
hi,
Firefox first apply the theme from `about:addons` page and after that applys the theme from any extension, if you choose the fuchsia from the extension so always be applied independent from the one you choose in the addons page.
Recently was a Firefox bug affecting the extension but was solved with the recent updated, if you are up to date that couldn't be a problem.
