### ISSUE TITLE
Side Panel Empty How Add Icon Like Your Screenshot And Open History Showing Add-On Icon

### ISSUE THREAD

**Issue by 0xl30** [Godiesc/firefox-gx#225]
How To Fix This Issue And I Want Add Rainbow Border Like Sweet-Pop Themes It Possible ?

![swappy-20241129-175937](https://github.com/user-attachments/assets/c1720ee5-fa48-41a1-95fb-69f890087fad)

**Comment by Godiesc** [comment]
hi,
for left sidebar you have the instructions here: [Left-Sidebar](https://github.com/Godiesc/firefox-gx/tree/main/Extras/Left-SideBar).
For the addon icon maybe you are using some '[Trick](https://github.com/Godiesc/firefox-gx/tree/main/Tricks)', I haven't test it in a while, maybe for now you can not use that trick.
And for a rainbow border I didn't try it, but I don't know if it could looks good cause the line using in this theme are 2: the first is the one around the tab-selected and the other is in bottom of all tabs, so sync that with a rainbow gradient seems difficult, I don't know.

**Comment by 0xl30** [comment]
iam follow all instructions but left side still empty...
![swappy-20241129-194140](https://github.com/user-attachments/assets/0a9e6324-d100-48d6-834b-b962f4bb5340)
![swappy-20241129-194213](https://github.com/user-attachments/assets/7a68491a-06bc-4319-9ed0-40278952d025)
adding code in ogx_tricks.css file but still empty

**Comment by Godiesc** [comment]
in Linux with Wayland the popup boxes are in wrong place, I can't fix that.
And For left-sidebar, let me explain, first yo should install the extension (all links to the extension are in the info page), after that you unpin the extension from the 'unified extension button', and after that in 'customization mode' you move your extension to the left-sidebar, in the info page you have all the icons I used for left-sidebar: 

![imagen](https://github.com/user-attachments/assets/6deffb6b-6270-424f-a98e-7dd9efb37a02)

**Comment by 0xl30** [comment]
![swappy-20241202-132723](https://github.com/user-attachments/assets/01840755-4d46-4342-bb34-a4447dd6af4d)
possible to make this type rainbow border ? and you have any discord server or chat group ? messenger extenstion removed .

**Comment by Godiesc** [comment]
> possible to make this type rainbow border ?

I tried before and didn't get it, so I didn't try it again.

> messenger extenstion removed

I saw that but I don't have time to make a new extension to replace it.

> you have any discord server or chat group ?

you mean a chat to talk about the theme or something like that? there is a [Discussions](https://github.com/Godiesc/firefox-gx/discussions) section in GitHub to talk when need it.
