### ISSUE TITLE
[Bug] Transparent context menu

### ISSUE THREAD

**Issue by acoustic-git-tar** [Godiesc/firefox-gx#41]
Right clicking anywhere on a page leads to a context menu that's transparent.
Expected behavior:
- Context menu is opaque.

Actual behavior:
- Context menu is transparent showing only the text.

System information
Firefox 109.0.1 (64-bit), Windows 10 (Similar issue on Windows 11 too)
Beautiful Opera GX Fuschia theme
Extensions are disabled and running default chrome file.
![image](https://user-images.githubusercontent.com/29723164/216748443-ce47f3f5-b12e-4b74-b3b1-2cb9a8df0274.png)

**Comment by Godiesc** [comment]
![imagen](https://user-images.githubusercontent.com/22057609/216772777-16d1f73d-5dac-46bc-858c-5421839278ec.png)

hi, I tested the theme and works fine, the contextual menu usually works bad if you use a third party theme of windows, i saw in your SS that the vertical gradient line in bookmarks-bar isn't there so you are using other code or something?

**Comment by acoustic-git-tar** [comment]
![image](https://user-images.githubusercontent.com/29723164/216775417-f14c2f32-51dd-4820-a6f9-51eff75815de.png)

That's strange. I used a current copy of the latest release as well as a clone of the git for the chrome/ folder, and the contextual menus are still transparent. 
I'm not using any third party theme besides just changing the Windows color accent. Could this be an about:config issue with 
toolkit.legacyUserProfileCustomizations.stylesheets being set to true?

**Comment by acoustic-git-tar** [comment]
Solved. Did some digging and layout.css.color-mix.enabled should be set to true.

**Comment by Godiesc** [comment]
In the steps to apply the theme say to copu the user.js too, in that file there are all the about:config rules you need to set.
