### ISSUE TITLE
Not a bug, just having trouble. Sorry.

### ISSUE THREAD

**Issue by NekoKatsune** [Godiesc/firefox-gx#42]
I downloaded the left side bar and treestyle addons, and now my tabs at the top of my browser are gone, and i can't figure out how to get them back while keeping the side bar and stuff. I'm also struggling to customise it and set it up but i can probably figure that out. Do you mind telling me how I can get my tabs back if possible? I'll keep trying to figure it out myself but i thought it might be worth asking

**Comment by Godiesc** [comment]
Hi, you can just delete the ogx_tree-tabs.css file from chrome>components folder. The tree style tabs style is for use with an extension, if you installed the extension you should enable it from the extension button on the right side next to windows controls.

**Comment by NekoKatsune** [comment]
i... had written a response and accidentally lost all of my tabs before sending it. i've just now recovered them. i don't understand the treetab thing very well and stuff lol. sorry. anyway. thank you for your (very very quick) response, and i'm sorry for the dumb question and stuff. I'll try doing that, i do have the tree tabs extension, though, but i wanted to try to have my tabs at the top of my screen again as normal but also potentially keep the treetab thing, or at least the sidebar. i was having trouble setting up the sidebar but again i think i can maybe figure that out, i just don't fully understand how to add stuff to it even after reading the README files. one thing i wish i could get that opera had was the ability to upload clipboard images when attaching files, as well as being able to see recent files. i don't suppose there's any way you'd be able to implement something like it in the future? 
i did find a similar extension for firefox, but it's not exactly the same and i haven't quite used it yet but it's also confusing me and not exactly the same as opera's. the reason i had the treestyle extension was to try to navigate my tabs a bit easier, because opera would normally shrink tab sizes and stuff as you add more and more, so that you can always see all of your tabs. i hadn't found something that does the same, but I'll keep looking.

![image](https://user-images.githubusercontent.com/127371919/223934952-9bf12843-0764-45c6-bca1-be519939e37f.png)
https://addons.mozilla.org/en-US/firefox/addon/clipboard2file/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

**Comment by Godiesc** [comment]
well...
in the "extras" folder you have all the files you need to add the features depending what you want, most of the times is add the files in chrome>components folder.
for the tabs to make small (you don't need the tree style feature) you could add some css  at the end of userChrome.css file like this:
```
/* Tamaño horizontal pestañas */
.tabbrowser-tab[fadein]:not([style^="min-width"]){ min-width: 30px !important; 
}
```

and for functions like the clipboard is something I cant do with css, you should find and extension that do that.

**Comment by NekoKatsune** [comment]
ah, alright, i guess i'll have to make do with the clipboard extension then. it's not that bad. thank you again.
i'm still having trouble setting up the left sidebar, it looks awkward and wrong for some reason, and it'd . i really don't understand it and i've read over the files several times.
i also don't really know how to code yet, but intend to learn at some point soon. i took a look at the "oneline" addon and i don't understand what it does or what exactly i'm supposed to do? could you maybe help me with that? i think that's all i'm having problems with. i appreciate the responses! 
![image](https://user-images.githubusercontent.com/127371919/224128609-7f3efd6e-60ed-4b89-95e5-e849e3e0146c.png)

**Comment by Godiesc** [comment]
well.. you really do not need to apply all the features from the "extras" folder, just what you want or need, the one-line config is for move up the toolbar next to the tabs-bar.

And the left sidebar, I can see in your screenshot, you apply it just right, if you wonder for the icons that I put in my preview it depends on the buttons you want to put right there. (right clic on the toolbar>customize toolbar and move the icons or extensions button to the left-sidebar).

I can see in your screenshot that the theme you use is from the extension: Firefox Color, if you use the images that the extension provide you will see a bad background in your selected tab.
