### ISSUE TITLE
Problem search bar

### ISSUE THREAD

**Issue by sandro696** [Godiesc/firefox-gx#44]
Hello to those who will read, I would like to know if it is possible to set the fire fox logo at the top and the search bar at the bottom because on my pc it displays them as in the attached photo. Thanks for the reply.

![Immagine 2023-04-02 120156](https://user-images.githubusercontent.com/129658094/229346088-9ed3c806-2164-4855-b0c1-ee5a3c2cf228.png)

**Comment by Godiesc** [comment]
hi, 
into the chrome/components/ogx_root-personal.css file there are a lot of customize rules, the one you want is the line 47.

**Comment by sandro696** [comment]
hello and thanks for your reply..so i downloaded a version that is not good? where can i find the version that works well? thanks for your reply.

**Comment by Godiesc** [comment]
![imagen](https://user-images.githubusercontent.com/22057609/229358807-cd505b3d-c5ea-40f6-9b5c-2d831ea90f3b.png)

but the problem you mentioned is the same, so you need to change the line I said you in my last comment after you download the theme correctly. Make sure to make a quick read in the main page to know the theme.

**Comment by sandro696** [comment]
hello I downloaded the new version but everything remained the same as before, and I can't find the string to change the central search bar on notepad.. other solutions? thanks.

**Comment by sandro696** [comment]
I was only able to change the main image and border color here is the screenshot.

![Immagine 2023-04-02 164024](https://user-images.githubusercontent.com/129658094/229359960-9ec51afe-b5e8-4d3c-b1cf-6b216ade40b3.png)

**Comment by Godiesc** [comment]
I said you to change the line 47, and restart the browser.

![imagen](https://user-images.githubusercontent.com/22057609/229360988-2c39e5d2-5dae-4f2c-b9c8-fc2676fb0cb2.png)

**Comment by Godiesc** [comment]
if you don't have how just replace that line with:

`--orientation-display: block ;`

**Comment by sandro696** [comment]
thanks for your advice..I couldn't fin
![Immagine 2023-04-02 171555](https://user-images.githubusercontent.com/129658094/229362084-beb2f096-a001-4b4f-9433-118d48fedb82.png)
d the row because I see it like this..

**Comment by sandro696** [comment]
thanks for your advice..I couldn't find the row because I see it like this..

**Comment by sandro696** [comment]
now it's perfect i just need to figure out how to change the display of the curves on the tabs

**Comment by Godiesc** [comment]
you should use a better program to open this kind of files, like [sublime text](https://www.sublimetext.com/).

**Comment by sandro696** [comment]
ok i will look for a better program

**Comment by Godiesc** [comment]
for the other tabs styles just follow the steps. https://github.com/Godiesc/firefox-gx/tree/main/Extras/Tab-Shapes

**Comment by sandro696** [comment]
ok thanks but i cant figure out how to download the file to install it..should i copy everything?

**Comment by Godiesc** [comment]
in the files you downloaded there is the "Extras" folder with all you need.

**Comment by sandro696** [comment]
Thanks for your info I couldn't find anything on the extras folder then I'll try again.

**Comment by sandro696** [comment]
hello and thanks for your advice..could you give me a hand to modify the curve of the cards?as you have seen, it is more difficult for me to identify the exact string for modification.

**Comment by Godiesc** [comment]
Try to share a screenshot for what you want, I don't know what is curve of the cards.

**Comment by sandro696** [comment]
hello and sorry if I didn't answer you right away personal problems..I asked you for a hand to optimize the opening pages aesthetically I wanted to change the shapes of the tabs..no I can change the tab-shapes thank you for your advice.
![Immagine 2023-04-08 094927](https://user-images.githubusercontent.com/129658094/230710241-91e5ebb0-5917-4e62-9035-a389ea0469a6.png)

**Comment by sandro696** [comment]
![Immagine 2023-04-08 095056](https://user-images.githubusercontent.com/129658094/230710280-fa9f3a94-db4a-40a4-a763-be944981c644.png)

**Comment by Godiesc** [comment]
hi, 
I said you that into the "Extras" folder you have all you need, for the tab-shapes just open the folder with that name and the files you need will be there, and in the github page you can clic it in "Tab hapes" to see how to apply.

**Comment by sandro696** [comment]
hello yes you told me how to do it but I see the page as in the photo and the program you recommended and sublime text. too hard for me to set up and understand.
![Immagine 2023-04-08 150723](https://user-images.githubusercontent.com/129658094/230722928-2e04e031-f76a-46ae-81c6-110e69626515.png)

**Comment by sandro696** [comment]
Is there any way to help me out?

**Comment by Godiesc** [comment]
you don't need to understand that code, I said you should open the github page to know how to apply.

![imagen](https://user-images.githubusercontent.com/22057609/230723071-e23c7233-fe97-4157-ad9c-ce229e891cee.png)

**Comment by sandro696** [comment]
nothing to do I tried but I can't understand the steps..thank you anyway..I'll leave everything as it is.
