### ISSUE TITLE
How can I move the extension icon to the left sidebar?

### ISSUE THREAD

**Issue by MuerteRoja** [Godiesc/firefox-gx#45]
![Captura de pantalla 2023-04-11 191639](https://user-images.githubusercontent.com/126993006/231253872-062c4a6a-a0d4-4472-a6ae-477e9e2eaa14.png)
Recently I have applied the Firefox GX issue, I have followed all the instructions but I would like to know how I can move the extensions icon to the left sidebar

**Comment by MuerteRoja** [comment]
![196332981-707d0b09-4e69-418d-a521-024c57f14745](https://user-images.githubusercontent.com/126993006/231285673-302ab918-0026-4c2f-8aec-7fccc7c0e40c.png)
Hello, good night, I have just taken this photograph of your forum, it seems that in your browser it has been possible to perform this action
![Captura de pantalla 2023-04-11 191639](https://user-images.githubusercontent.com/126993006/231286155-bccdc540-e77a-4965-b2fa-9c4573cb16d0.png)
![Captura de pantalla 2023-04-11 2154554](https://user-images.githubusercontent.com/126993006/231286161-c8e7c5a8-9d21-47d6-b3ea-994c35f6954c.png)
![Captura de pantalla 2023-047-11 215512](https://user-images.githubusercontent.com/126993006/231286165-549429a3-9e77-4829-9316-a721c53e8330.png)
I also take the opportunity to comment that I have placed on my user profile the User.J file I have placed it in both folders (not knowing well in which folder to place it, I placed it in both, I did the same thing with the chrome folder)

**Comment by Godiesc** [comment]
that screenshot is from a old browser version of the browser, I didn't update all the images in the github page, so little details like that don´t be in the current release, sorry for the inconvenient. 

and for the profile folder I always use `about:support` like in the [image posted in the repository.](https://user-images.githubusercontent.com/22057609/156908375-824f8679-56a5-4d09-a86f-353a7f61135e.png)

**Comment by MuerteRoja** [comment]
I understand, thanks for the clarification

PD: Sorry, I had forgotten to answer this last issue, I am currently using the Librewolf browser, which is a Mozilla Firefox fork, I really like it because it sends much less telemetry than Firefox, here I will leave you some articles in case you are interested see them 
Article 1: https://spyware.neocities.org/articles/librewolf
Article 2: https://spyware.neocities.org/articles/firefox

**Comment by Godiesc** [comment]
I understand, if you use other browser maybe will apears some issues, the one I noticed was the newtab button, it seems tight, just that.

**Comment by MuerteRoja** [comment]
I really thank you for answering the questions, you have really helped me understand many things, I just have one last question, before you mentioned that maybe in the next update you release this topic, you will put the extensions button in the sidebar by default left Is there a way that I can be notified of such an update?

**Comment by Godiesc** [comment]
well, you should check the repository when the next release of the browser arrives, I usually update the theme to fix bugs or add features like the one you want.

**Comment by MuerteRoja** [comment]
How often the updates are usually published? monthly?

**Comment by Godiesc** [comment]
in Firefox is about 30 days, see here: https://whattrainisitnow.com/calendar/

**Comment by MuerteRoja** [comment]
So you would be publishing the release of this theme in the month of May

**Comment by Godiesc** [comment]
yes

**Comment by MuerteRoja** [comment]
Okey

**Comment by Godiesc** [comment]
I updated the tricks section and added the code to move the "extension button" to the left-sidebar, but always will be in the top of the icons. [The trick is here](https://github.com/Godiesc/firefox-gx/blob/main/Tricks/README.md#extensions-button-into-the-left-sidebar---immovable).
