### ISSUE TITLE
Having trouble with the left sidebar

### ISSUE THREAD

**Issue by lucascompython** [Godiesc/firefox-gx#47]
When installing the [Messenger](https://addons.mozilla.org/es/firefox/addon/sideapp-for-messenger/) extension when login in, it appears like this ![image](https://user-images.githubusercontent.com/77930083/231828585-13f4e455-117b-43dc-87c6-5517fe0e66d4.png)
Just like Opera, and that's how I want it, but after I login and put the extension on the sidebar and click to open Messenger it opens a whole new window with messenger (I'm obviously not showing a picture of it because of privacy reasons).  Also happens with the [WhatsApp](https://addons.mozilla.org/es/firefox/addon/whatsapp-messenger/) extension.

**Comment by Godiesc** [comment]
hi, 
As you know, the theme is just to change the appearance of the browser, I'm not capable to do the same for the extensions like in Opera browser, I can't duplicate the same functions in Firefox, I tested some extensions just to change the icons to give them the appearance like in Opera but I can't give them functions or something similar.
I'm not an extension developer to create extension that has the same functions in Firefox.

And for the facebook extension sadly you should open the sidebar first with this button:
![imagen](https://user-images.githubusercontent.com/22057609/231841070-498d19d6-8af5-4d21-b601-c25cf22585b9.png)
 
and choose  "messenger" in the menu if isn't active.

**Comment by lucascompython** [comment]
Oh ok, I understand, thank you for your quick response!
