### ISSUE TITLE
Visual Bugs on new update v113

### ISSUE THREAD

**Issue by GrPK** [Godiesc/firefox-gx#48]
Hello, added screenshot (I think it's enough to see what I'm talking about)

![image](https://user-images.githubusercontent.com/31523635/231888503-cb6f74bc-c341-463d-8a57-bc50bdcaed6a.png)

**Comment by Godiesc** [comment]
hi,
I updated the files `ogx_menu.css` and `ogx_left-sidebar.css` for problems with the next release of the browser, but you should know the theme is compatible only with release version of Firefox.

![imagen](https://user-images.githubusercontent.com/22057609/231905047-74ba8440-dee2-4a68-ac3c-2e523c181220.png)

I tested the tab-shapes and if you have a bigger tabs height the newtab button is closer to it, but not so much like in your Screenshot, are you sure you are using the theme updated?

![imagen](https://user-images.githubusercontent.com/22057609/231905000-1c66676f-390e-4e86-8a05-f8b3f144b6b8.png)

**Comment by GrPK** [comment]
Hello, yes, I use the latest update (Downloaded as zip your repo). The menu is fixed, but the plus button is still waay to close to tab
I dont use any other custom settings (Screenshot attached) . Maybe I can edit something?

**Comment by Godiesc** [comment]
in the line 57 of `chrome/components/ogx_tab-shapes.css` replace with this:

`padding-inline-start: calc(var(--uc-margin-left-newtab) + 10px) !important;`

**Comment by GrPK** [comment]
Thanks, it worked like charm!
