### ISSUE TITLE
ogx_left-sidebar.css not working

### ISSUE THREAD

**Issue by Giuszm** [Godiesc/firefox-gx#50]
Even though i've created a components folder inside the chrome folder the left side-bar doesn't show up. Yes i've already enabled the "always show" option for the bookmarks toolbar. Why doesn't it work?

**Comment by Godiesc** [comment]
hi,
fist of all you you shouldn't create the `components` folder, the folder already exist, into the folder you should see all the css files that the theme uses, maybe are you open the wrong folder?

**Comment by Giuszm** [comment]
Yeah i saw that and i reinstalled a clean copy of the operagx theme so the components folder was there, but even then when i followed the instructions in order to add the left sidebar it still didn't work, why?

**Comment by Godiesc** [comment]
You need to share a ScreenShot to see how is your theme now.
