### ISSUE TITLE
Application menu label is misplaced

### ISSUE THREAD

**Issue by khalid-codes** [Godiesc/firefox-gx#51]
I'm using Firefox Developer Edition 113.0b4 (64-bit) on Windows 11. After updating the browser I've noticed that the 'Menu' label in under the Firefox icon. And the label is not visible when I open the menu.

The label is under the Firefox icon instead of on it's side.
![image](https://user-images.githubusercontent.com/67034266/232758159-04f05733-d943-454f-acea-a3a2e1374c2a.png)

When the application menu is open, the label is hidden under the menu.
![image](https://user-images.githubusercontent.com/67034266/232760031-5e1aa7c3-8da5-4c05-87cb-608f2bec1999.png)

**Comment by Godiesc** [comment]
hi,
You should know that the theme works fine only in the release version of Firefox, the current version v.112, make the theme compatible with beta, developer or nightly version is a hard work for me so I don't even try, actually I'm am on he road of fixing the theme for the next release and I updated the theme but you will need to use `code->download zip` to get the latest updates, and for this days I will update several times until I fix all the bugs.
