### ISSUE TITLE
My Background Image on The Top Screen Doesn't Align with The Page

### ISSUE THREAD

**Issue by SakuraEyes** [Godiesc/firefox-gx#52]
Hello, I'm sorry to bother you. I'm trying to get my theme set up but once I placed my back ground image, I can't get it to align with the tab menu up top. Is there a specific line of code I need to tweak for it? I'm new to coding so again, my apologies
![Screenshot 2023-04-18 150240](https://user-images.githubusercontent.com/122223651/232892832-5590ec63-bf85-4f35-abe4-15876e235bc4.png)

**Comment by Godiesc** [comment]
hi, 
I assume you are using the extra "Main-Image" config, and you putted the 2 files into the `chrome->components` folder.
but doing that the image should align without any problem. I will tested right now to see if there is a problem.

**Comment by SakuraEyes** [comment]
I deleted the Main-Image config and copied it again into the components, everything seems to look okay except near the top left.

![Screenshot 2023-04-18 175107](https://user-images.githubusercontent.com/122223651/232922421-0b2283a9-1ff2-4536-be34-348311ea1635.png)

**Comment by SakuraEyes** [comment]
My display is 1920 px x 1080 px and the background image is 1200 px x 850 px. It's most likely that, it's just that I don't know how to fix it lol

**Comment by Godiesc** [comment]
Thats the problem, for that config you needs an image at least the same width and 150 px more in height, you need to get a bigger image, test with a new image and you won't see any problem.

**Comment by Godiesc** [comment]
the way this Main-image config works cant make the background expand to the size of your monitor resolution without making a mess with the background in selected tab, for that you need to use an image bigger enough to the config works fine. I added more info for that in the description of the Config. In the [Tricks ](https://github.com/Godiesc/firefox-gx/tree/main/Tricks) section there is a way to make the left-sidebar solid, maybe works better for you to get that way.

**Comment by SakuraEyes** [comment]
Alright, thank you again so much! Hopefully I'll get more of this when I try to get into coding lol
