### ISSUE TITLE
Problem with One Line

### ISSUE THREAD

**Issue by MuerteRoja** [Godiesc/firefox-gx#53]
https://user-images.githubusercontent.com/126993006/233875525-24d5b49c-6def-4b51-ad34-00fd8347ba56.mp4

Hello good evening, today I tried to apply the OneLine theme in my Librewolf 112.0.1-2 browser and, however, I have been presented with this bug, I cannot search, since the windows are overlapped on the search box, the option would be to apply the first option, use the address bar to search, but the issue is that in the about:config section I have configured my web browser so that searches cannot be carried out from the address bar, hence I need to use the second option of using the search bar which is right next to the address bar can you fix this bug please?

**Comment by Godiesc** [comment]
hi,
sorry for the problems but the theme don't support that second search box, and I don't think I could make it compatible in the future, and I see other visual problems in your SS, maybe isn't compatible with Librewolf, I only tested in Firefox.

**Comment by MuerteRoja** [comment]
ok thanks anyway
