### ISSUE TITLE
Tabs are gone and new sidebar appeared

### ISSUE THREAD

**Issue by DJSchaffner** [Godiesc/firefox-gx#59]
I couldn't find any note on this but when i just installed the newest version to fix the issues that came up in the latest firefox release, I now no longer have a tab bar (so I have no idea which other tabs are open.. I can however still switch with ctrl+tab) and there is now a small empty sidebar on the left.

Are these intended features? If so, how can I bring back my tabs?

**Comment by DJSchaffner** [comment]
Removing these files from the components folder fixed it for me:
- ogx_tab_center_reborn.css
- ogx_left-sidebar.css
- ogx_tree-tabs.css

I think those might be components from the <extras> folder which were previously not included in the default list. Maybe you added them by accident?

**Comment by Godiesc** [comment]
hi,
thanks for your report, I will fix the download files from "release" section now, you can use: code->download zip for the moment with no problems.
