### ISSUE TITLE
Bookmark toolbar error after 113 update

### ISSUE THREAD

**Issue by zioroiwi** [Godiesc/firefox-gx#63]
I'm sorry about my English. Last night after updating to version 113, my bookmark toolbar had an issue, only displaying 2 icons horizontally as in the image. I don't know what the problem is, does anyone have any suggestions?[](url)
![Screenshot from 2023-05-12 10-09-19](https://github.com/Godiesc/firefox-gx/assets/70985002/7c56843d-7ec4-4b28-8f0a-dde1a07124f1)

My bookmark toolbar look like this

![Screenshot from 2023-05-12 10-12-21](https://github.com/Godiesc/firefox-gx/assets/70985002/c6ad4293-06c9-4807-b8a8-4186c5235aff)

I have tried reinstalling Firefox and reinstalling the theme but it was not successful.

**Comment by Godiesc** [comment]
hi, 
you need to update the firefox-gx theme with the latest update. 
https://github.com/Godiesc/firefox-gx/releases/tag/v.7.9

**Comment by zioroiwi** [comment]
> hi, you need to update the firefox-gx theme with the latest update. https://github.com/Godiesc/firefox-gx/releases/tag/v.7.9

I have tried copying the Chrome folder and user.js to the Profile Directory folder, but it didn't work. I also tried reinstalling Firefox. Do I need to delete the entire Profile Directory folder and reinstall the theme?

**Comment by Godiesc** [comment]
no, it's just the chrome folder you need to replace, be sure you are doing in the correct profile folder.
![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/51503cbf-a147-4b5d-8125-8018af054639)

**Comment by zioroiwi** [comment]
thank you, its worked

**Comment by Godiesc** [comment]
you're welcome.
