### ISSUE TITLE
Adding Extension

### ISSUE THREAD

**Issue by modz2014** [Godiesc/firefox-gx#65]
hey any chance of adding extension to a side bar like opear does example ith ChatGPT so it opens it a small window on the side and click to close or click again opens

**Comment by Godiesc** [comment]
hi,
if you have an extension just put the icon into the sidebar: https://github.com/Godiesc/firefox-gx/tree/main/Extras/Left-SideBar
or what do you mean?

**Comment by modz2014** [comment]
well if you look at opera ChatGPT extension you will understand it more

**Comment by Godiesc** [comment]
if is an extension I can't do anything, CSS theme like mine is just for the look of the browser, not to dd features, you need to search in the firefox add-ons store if exist the same extension or something similar.

**Comment by modz2014** [comment]
nar there is noty a extension i have created the extension but I want to add it to the side bar not for bookmarks

**Comment by Godiesc** [comment]
mmmm, you can see that my theme use the bookmark-bar to simulate the left sidebar that has Opera-GX, and you can add there the extension icons and use them from there, if you want an extra bar and keep the original bookmark bar well that maybe is possible if you create an extension that add and extra bar, I'm not an extension developer and I don't know if  that is possible.
