### ISSUE TITLE
Context menu and other 'menu' content on windows is too large, theme overrides website styling

### ISSUE THREAD

**Issue by arijitroy454** [Godiesc/firefox-gx#68]
The context menu options are too large in windows
![image](https://github.com/Godiesc/firefox-gx/assets/130592316/62a04096-8407-4dd8-acdf-78e543c23de8)
![image](https://github.com/Godiesc/firefox-gx/assets/130592316/39370166-bcd4-4d0a-bdc0-ec087825a735)

This also happens with other menus in certain websites, where this theme overrides the default menu with a very large and fat menu.

This is the default menu on myanimelist
![image](https://github.com/Godiesc/firefox-gx/assets/130592316/2638973d-9f2b-4d2a-9669-e0ecd129df56)

And this is what this theme replaces it to be like. This is too large, too wide and fat, and I feel there is no need to replace.
![image](https://github.com/Godiesc/firefox-gx/assets/130592316/e526b5d4-c20a-43a4-bbcf-f3210bc5dc06)

I also feel that replacing the default placeholder text for 'My Account' written in a weird font with this looks much better. Imo the font looks very out of place.
![image](https://github.com/Godiesc/firefox-gx/assets/130592316/2c456ab0-db69-448a-bba1-a356438e72d1)

![image](https://github.com/Godiesc/firefox-gx/assets/130592316/1bbd13ba-e0d4-4d44-8083-5502739799a7)
Either this or just "Firefox Account" in normal font

**Comment by arijitroy454** [comment]
Got it, and yes the css change fixed the issues for me.

Question, is there a way to decrease the size of the size of this menu aswell?
![image](https://github.com/Godiesc/firefox-gx/assets/130592316/8d36fc8d-7a8a-48b0-b79d-dcc6f73bbe8d)

**Comment by Godiesc** [comment]
this is a code I will add in the next release version of the theme:

```
#ContentSelectDropdown > menupopup > menuitem {
  padding: 0 6px !important;
}
```
