### ISSUE TITLE
Autoscrolling icon is cut from the side

### ISSUE THREAD

**Issue by arijitroy454** [Godiesc/firefox-gx#69]
![image](https://github.com/Godiesc/firefox-gx/assets/130592316/33231653-5ac8-4dd3-b5af-510a6374bee5)

**Comment by arijitroy454** [comment]
The autoscrolling icon looks like this. I dont remember it being like this before. Maybe a new issue.

**Comment by Godiesc** [comment]
hi, 
I updated right now the file [ogx_arrowpanel.css](https://github.com/Godiesc/firefox-gx/blob/main/chrome/components/ogx_arrowpanel.css) to solve the problem.

**Comment by Godiesc** [comment]
Solved in the new release, thanks for report it.
