### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by gamefree111** [Godiesc/firefox-gx#71]
Hello
I am a Persian speaker and I use Persian language in Firefox.
Your css has a problem. When I right-click, 3 incorrect words are displayed:
![image](https://github.com/Godiesc/firefox-gx/assets/135963438/8801f715-a137-404f-a34a-cf957c65c8d3)
(It seems that there is a problem with how to display right to left)
Thank you for your efforts

**Comment by Godiesc** [comment]
hi,
make compatibility for that lenguajes is hard mor me, I don't use it so I can't tested, de base theme could work with a little problems but all "Extra" features I think it don't work at all.
For the problem in the contextual menu you can replace the code of the file: `ogx_contextual-menu.css` with the code from here: https://pastebin.com/ZLfHHnnM

**Comment by gamefree111** [comment]
thank you. The problem was solved.
Of course, I activated some extra features and it works properly.

**Comment by MuerteRoja** [comment]
Se te notó un poco ahí el spanenglish Godiesc, justo cuando dices "I can't tested, **de** base"
