### ISSUE TITLE
help with Tab-Shapes

### ISSUE THREAD

**Issue by soilentgreen** [Godiesc/firefox-gx#73]
hi  to all.
I'm using libreWolf and I the tab shape wont work.
I attached pic. 
hope you can help please. 
![1](https://github.com/Godiesc/firefox-gx/assets/7990597/7e613a40-1211-4c1b-a25f-0ab0bbeed5aa)

**Comment by Godiesc** [comment]
hi,
be sure to follow all the steps to apply, maybe you didn't copy the `user.js` file into your profile folder.

**Comment by soilentgreen** [comment]
hi
many thanks for your help :-)
what fix it is to copy paste ogx_main-image.css and ogx_root-personal.css into the chrome/components folder.
but now the image is too big and I cant make the Main-Image to work. 

I tried to Fast step to apply the config but it wont work. 

its hatd to understand what I need to do.

![1](https://github.com/Godiesc/firefox-gx/assets/7990597/9ac420b1-de4d-4251-b136-c7214086a391)

**Comment by Godiesc** [comment]
tab-shapes should be work fine without adding "Main-image" config.
and for your next question you need to resize the image to the width of your monitor, Main-image config need that to works property, you will see in the "Notice" section:

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/1ba1b715-a4c3-4046-a7a0-f86bb53ace7e)

be sure to reed that part.

**Comment by soilentgreen** [comment]
Hi ,

So I add the files ogx_main-image.css and ogx_root-personal.css into the chrome/components folder.
Next I resized the image to 1920X1080. my monitor width.
Next I deleted line 67-74 from ogx_main-image.css because I  use left sidebar.
Without success.

So I tried to do the manual steps to apply the config.

*Edit the line 31 into the ogx_root-personal.css file with the code: --wallpaper-size: auto auto ; - to what need to change?
*Edit the line 21 into the ogx_root-personal.css file with the code: --brightness-wallpaper: brightness(51%);. to what need to change?
*Edit the line 56 into the ogx_root-personal.css file, uncomment it and write the right number, there is a description on the right side of the rule, - what is the right number?

hope you can help.

**Comment by soilentgreen** [comment]
expect to get full pic as yours.
![1](https://github.com/Godiesc/firefox-gx/assets/7990597/3de81bad-71af-4be2-b821-f7a424cf57e0)

**Comment by Godiesc** [comment]
in this image you shared the color of the tabs is the same form the left sidebar, that's ok.
![253929216-7e613a40-1211-4c1b-a25f-0ab0bbeed5aa](https://github.com/Godiesc/firefox-gx/assets/22057609/3baadd21-150e-4fc0-bfee-2a5d0c8f4ae0)

But in the second image you shared, the color is different, maybe you are editing the code in the wrong way, try to start again and see if that is a problem.
![253979275-9ac420b1-de4d-4251-b136-c7214086a391](https://github.com/Godiesc/firefox-gx/assets/22057609/ee9de456-10c4-499c-a349-0abc4fb265bd)

In this image is like you never active the last code from the code ( delete line 67-74 from ogx_main-image.css).

![254040247-3de81bad-71af-4be2-b821-f7a424cf57e0](https://github.com/Godiesc/firefox-gx/assets/22057609/ceb72453-5333-4e3f-91af-cb1ae5a9b522)

and something to consider is that I test my theme only in Firefox, if something isn't compatible with librewolf I don't know, be sure you download the theme in the right way.

**Comment by Godiesc** [comment]
maybe you are deleting all the code block and that not right, you need anly delete the line 67 and the line 74.

**Comment by soilentgreen** [comment]
Many many thanks man!
it was the code, I deleted it wrong.
thank you for helped me and for this beautiful theme :-)
![Untitled](https://github.com/Godiesc/firefox-gx/assets/7990597/cf9aab0d-6274-4b11-95ef-1c9f17a9c978)

**Comment by Godiesc** [comment]
you're welcome, it seems to not align correctly but that could happens for librewolf differences for firefox, maybe you have the Windows task bar in the sides od the screen, or the image is not of width of your screen; but at least you solved, I see in your Screenshot the top of the browser is cut and the window controls are outside the border.

**Comment by soilentgreen** [comment]
yes it because even though my screen resolution is 1920X1080 big part of the image is cut (the image is too much close up at 1920X1080). so I low down the resolution until I could see most of the image. 
the image resolution I use with the theme is 1500X843.
I do not why  it happen.

**Comment by Godiesc** [comment]
your image should be 1920X1080, surf in internet for a perfect image jeje well I hope everything else is fine. :)

**Comment by soilentgreen** [comment]
now I think its perfect. the problem was the scal and layout under display of windows. it was on 125% instead of 100% 
![1](https://github.com/Godiesc/firefox-gx/assets/7990597/4eacbfce-f9e3-4924-b187-98a679d40432)

**Comment by Godiesc** [comment]
i'm glad, perfect. 👍
