### ISSUE TITLE
Tricks and settings questions

### ISSUE THREAD

**Issue by soilentgreen** [Godiesc/firefox-gx#74]
Hello again Godiesc, 

Have some questions hope you can help me with:

1) I try to do the "Image in menus (contextual menu and arrowpanel menus)" trick but it won't work.
I copy past the code to  ogx_tricks.css and put it in components.
Do I need to add image to anywhere for it to work?

2) Can we change the background of "settings" to  black from dark? and change the fonts to another color?

3) Something you might wanted to know. When I did the "Extensions button into the "left-sidebar" ", it worked the button moved left but on the first icon I have on the sidebar. The only fix for me was to change the code from "top: 76px !important;"
to "top: 395px !important;" and it moved it below my all icons. When I tried to move it above my first Icon it look bed because it was too close to the "menu" icon.

Thank again

**Comment by Godiesc** [comment]
hi,
1.- "Image in menus (contextual menu and arrowpanel menus)" trick works in themes that have images, try one and let me know if works, for example this: https://addons.mozilla.org/es/firefox/addon/beautiful-red-blur/

2.- I don't understand the second question, try to show a screenshot and some annotation to see what you want, what font color(all the font color or of some section or...), aand change black to dark is the same meaning for me, maybe you wrote wrong.

3.- The extensions button should be position in the top of the sidebar below the menu button (as it shows in the preview image), I will test soon.

**Comment by soilentgreen** [comment]
hi 
1) didn't work with Beautiful Red Blur theme. attached the ogx_tricks.css maybe the code not right?  
[ogx_tricks.zip](https://github.com/Godiesc/firefox-gx/files/12097886/ogx_tricks.zip)

2) attached image of the settings.  can we BG it in pure black? and can we color the font in red?
![1](https://github.com/Godiesc/firefox-gx/assets/7990597/dc565020-8d41-4530-9cbb-ebdb3eb8ba5e)

3) attached image of the Extensions when it on 76px. as you see the Extensions is on the setting button.
![2](https://github.com/Godiesc/firefox-gx/assets/7990597/379ad2cf-b3f9-41b1-b705-56f74585deb8)

**Comment by soilentgreen** [comment]
hi and many thanks :-)
I started with 2. 
can you tell me the line you changed?
I changed to black lines 71 and 72
and for the red font  56, 57 and 92
there is one line of black BG I cant find.
![1](https://github.com/Godiesc/firefox-gx/assets/7990597/f8d65484-4671-4332-ad1c-ff05de937fb2)

**Comment by Godiesc** [comment]
I added this code block after line 176 :

```
/* color fondo grande */
    .main-content{
    background: black !important;
    color: red !important;
}
```

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/76d83e57-d5e8-42c2-907a-3e69867eed23)

**Comment by soilentgreen** [comment]
about the bg settings  it worked thanks to you
![1](https://github.com/Godiesc/firefox-gx/assets/7990597/f81eda7b-25a2-4d4a-bb6a-4857fc8a88ff)

about the extensions, 182 and bigger numbers didn't work. the icon didn't moved.  but its fine I like how it look with "top: 395px !important;"

About the "Image in menus" it didn't work. 
you told me that the first line of the code is wrong. but i copy past the code as it is, 
 and it look as the pic you upload. and so is mine:  
![11](https://github.com/Godiesc/firefox-gx/assets/7990597/f1f5a4a3-a1d1-43ec-bfb5-6fde9e80decf)

**Comment by Godiesc** [comment]
`you told me that the first line of the code is wrong. but i copy past the code as it is` 
I said you the first line of your file, and I don't know if having that affects the fist code block and for that the change to 182 didn't work for you.

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/dc7c05fc-486c-4d3c-8520-27d82b289472)

**Comment by soilentgreen** [comment]
Godiesc about the icon its no big deal.
it is possible the  "Image in menus" don't work because of firefox color? I tried with this theme too.
https://addons.mozilla.org/en-US/firefox/addon/beautiful-gx-fantasy/
and thank you very much for help me :-)

**Comment by Godiesc** [comment]
try to keep a good format of the css or the code will fail in ways you can't image jeje

The code for move the extension button works fine, the button is moved to the top icons in the left-sidebar.

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/58207a4a-36b9-4faf-9f86-6afa5d36f9f9)

for the contextual menu the code works fine, but is a little opaque, so maybe you should try the new number in the lines that a mark in the next picture, to make the image more visible.

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/ca0ef3a1-e280-437c-9378-e83bea084c90)

**Comment by soilentgreen** [comment]
hi
so now the Extensions button move as it should :-)

but the contextual menu the code wont work.
I notice that my themes look different than yours. I do not have the red blur as yours. maybe it block some how?
look at the pic only black:
![Untitled](https://github.com/Godiesc/firefox-gx/assets/7990597/f7ab61fe-8f16-4b52-b6c8-e84186103857)

**Comment by soilentgreen** [comment]
yes when I turn off  fire fox color  Image in menus works. that was the problem.
thank you for your help. again :-)

**Comment by soilentgreen** [comment]
thank you for that!!!  :-)
Godiesc, I must tell you, you are one of the most helpful and tolerant devs I ever see. there is few, but not a lot.

thanks for your help  and for help me create so beautiful theme :-)

I wish I could use firefox color with  "Image in menus" trick but If I should choose, firefox color gives a lot more customization from that trick.

**Comment by Godiesc** [comment]
Anytime. 
If you know basic css and use the console of the browser you can change everything in the browser. :)

**Comment by soilentgreen** [comment]
no I do not know...

By the way maybe you want add to the "Image in menus" trick page, that it wont work with firefox color, because  on the main page of the theme you recommend to use firefox color. just a thought.

**Comment by Godiesc** [comment]
I will put a warning in that style, thanks for the advise.

**Comment by soilentgreen** [comment]
Hi Godiesc,

There's few places I want to changed the font color to red.
(Just so you know if you don’t have time its fine, you helped me so much already so I’ll understand  :-) )
This is the places: 
1) New tab
2) Search bar
3) Close confirmation
Thanks again.
![1](https://github.com/Godiesc/firefox-gx/assets/7990597/4eff7782-3466-4359-ad6b-6a53bd5e8671)
![2](https://github.com/Godiesc/firefox-gx/assets/7990597/044d7bac-fe6a-41a7-b21f-26f5d0fc99c3)
![3](https://github.com/Godiesc/firefox-gx/assets/7990597/5f050275-f71c-45b5-b8ea-9f4c431c6ec9)

**Comment by Godiesc** [comment]
hi,
in `ogx_root.css` you will find a lot of variables that change the colors in general for dark and light mode.

the line 18 will solve your solve 1-2-4 of your question.

`--lwt-tab-text: #ff0000 !important;`

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/95c03cf0-0fff-4eb3-9fe3-aa54b1779127)

for "3" the easy way is to change the line 36 but will affect other text and change to red too. Tested and see if all seems fine.

`--newtab-text-primary-color: #ff0000 !important;`

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/294ebbd6-48d8-400c-99a0-a4f67f19542b)

for "5" you need to use the `ogx_notifications.css` and add a line after line 17:

`--in-content-page-color: red !important;`

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/3be1f295-d274-4dab-ac37-0edc04e2cb4e)

**Comment by soilentgreen** [comment]
Worked like a charm :-) Thank you !!!
![1](https://github.com/Godiesc/firefox-gx/assets/7990597/6e7a0113-1083-43d4-b896-58f3dc37d703)
There is a way to color  the  "Close tabs" to black and the "Cancel" to red?
![2](https://github.com/Godiesc/firefox-gx/assets/7990597/f79dbdbb-e20c-46aa-83e5-fcf8f446b835)

**Comment by Godiesc** [comment]
From the line 74 replace that code block with this:

```
    --in-content-primary-button-background: black !important;
    --in-content-primary-button-background-hover: var(--general-color) !important;
    --in-content-primary-button-background-active: var(--button-active-bgcolor) !important;
    --in-content-primary-button-text-color: white !important;
    --in-content-button-background: #ff0000 !important;
    --in-content-button-background-hover: #ff3030 !important;
```

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/247b0287-6768-4e50-8b79-07383049d252)

**Comment by soilentgreen** [comment]
Didn't work 
![1](https://github.com/Godiesc/firefox-gx/assets/7990597/5db6c964-7863-4f97-a8b5-4ee95c48d6e3)

**Comment by soilentgreen** [comment]
So I changed the close tab font.
can I change the cancel font to red?
![1](https://github.com/Godiesc/firefox-gx/assets/7990597/29406299-00e0-4a8a-9074-bd542b567f0c)
![Untitled](https://github.com/Godiesc/firefox-gx/assets/7990597/20b1fe00-b49a-4870-a969-6f6910df5f93)

**Comment by Godiesc** [comment]
This could work.
`--in-content-button-text-color: red !important;`

**Comment by soilentgreen** [comment]
hi Godiec,
so with your help I somehow succeeded to make it as I wanted :-)
thanks again (and again) for your help.

https://github.com/Godiesc/firefox-gx/assets/7990597/62801eaf-c0e7-43bb-af76-8f3bf886b42d

`--in-content-primary-button-background: var(--button-active-bgcolor) !important;
--in-content-primary-button-background-hover: var(--general-color) !important;
--in-content-primary-button-background-active: var(--button-active-bgcolor) !important;
--in-content-primary-button-text-color: black !important;
--in-content-button-background: #343d46 !important;
--in-content-button-background-hover: #BF0609  !important;
--in-content-button-text-color: red !important;
--in-content-button-text-color-hover: black  !important;`

**Comment by Godiesc** [comment]
You're welcome.
