### ISSUE TITLE
Firefox-gx for Floorp browser ?

### ISSUE THREAD

**Issue by minlmao** [Godiesc/firefox-gx#75]

**Comment by Godiesc** [comment]
Hi, the theme was made for firefox, with derivates you should try it and see if works or not.

**Comment by surapunoyousei** [comment]
Plz set your design to Firefox Proton, After that You can install Firefox-gx. maybe.

**Comment by minlmao** [comment]
Sorry for reopening the issue again. When I apply `ogx_left-sidebar.css` on Floorp, the theme is applied on bookmark bar instead of Floorp's sidebar.
![Screenshot 2023-08-05 105748](https://github.com/Godiesc/firefox-gx/assets/87901700/ee90387e-406e-4961-8fed-047fa8d91ab9)

**Comment by Godiesc** [comment]
Hi, the "left-sidebar" config works with the bookmarks-bar, firefox don't have that extra bar so my theme don't use it.

**Comment by minlmao** [comment]
Oh, that's sad. Do you plan to make new ogx_left-sidebar.css for Floorp in near future?

**Comment by Godiesc** [comment]
I don't know, the future is unpredictable, maybe, who knows, I should download another browser and.... jeje
