### ISSUE TITLE
theme resetting

### ISSUE THREAD

**Issue by featherice** [Godiesc/firefox-gx#78]
Clean firefox install. First i installed firefox gx (placed user.js and chrome folder), everything worked. Next i added and turned on one of recommended themes (purple), it applied correctly. Then i restarted firefox, when it loads it uses new theme, but after finishing loading tabs accent color resets to default fuchsia.

**Comment by Godiesc** [comment]
hi, 
that could happen when you have other extension that change the theme colors like "Firefox color" or other, or if you have other installations of Firefox in other version (beta, nightly, etc) , when Firefox try to sync the theme, the theme reset to the default (system theme - automatic).
