### ISSUE TITLE
sidebar autoshrink feature request

### ISSUE THREAD

**Issue by featherice** [Godiesc/firefox-gx#79]
It seems that firefox gx custom css takes control over other css hacks when working with Sidebery. Therefore i ask to add an option in your css extras for autohiding Sidebery (beta).

**Comment by Godiesc** [comment]
hi,
In sidebery I only give it a background image for fun jeje, I don't have the plan to add any code for customize that extension cause it depends of what the user wants, the same happens with Tree Style Tab extension. If you want an autohide I guess there are code for that here https://www.reddit.com/r/FirefoxCSS/comments/pcuir9/sidebery_hideshow_sidebar_when_hovering_very/
