### ISSUE TITLE
Tabs not aligned with sidebar

### ISSUE THREAD

**Issue by Naile7477** [Godiesc/firefox-gx#80]
Tabs with Sidebar buggy on newest Firefox version (117.0 (64-Bit))
![grafik](https://github.com/Godiesc/firefox-gx/assets/67003003/768a0b0e-53f2-41e7-8c8d-32e6bb386a79)

**Comment by Godiesc** [comment]
hi,
what Operative system are you using? I don't see the hamburger menu in your Screenshot, maybe MacOS?

**Comment by Naile7477** [comment]
i'm using the Windows 11 (22H2) and my hamburger menu were all the time on the left, i thought that was normal until now
![grafik](https://github.com/Godiesc/firefox-gx/assets/67003003/6c541949-8d48-4df7-9eda-ca1667f80ea5)

**Comment by Godiesc** [comment]
maybe you are not updated the theme, with Firefox 117 some OS rules stopped to work. You should download the theme from here: https://github.com/Godiesc/firefox-gx/releases/tag/v.8.3

**Comment by Naile7477** [comment]
it worked, thank you
