### ISSUE TITLE
This theme conflicts with "clipboard2file" extension

### ISSUE THREAD

**Issue by zWolfrost** [Godiesc/firefox-gx#81]
I had just installed "clipboard2file" extension (to emulate the behavior of opera gx "select clipboard image" feature) when I found out that this theme would conflict with it (see image below)

![](https://user-images.githubusercontent.com/101343066/264081218-0fb474d5-ef06-4f5b-b6df-9b2225159f79.png)

Specifically, the culprit lines are "6" and "30" from "ogx_UC-settings-addons-pages.css" and lines "561" and "568" from "ogx_UC-newtabpage.css".

If these lines can be removed or replaced in a way that doesn't conflict with this extension i would really be happy (even though i don't know what they are for). But even if they are important in some way, i felt like noting that out for people who have the same problem.

Please close this issue if nothing can be done about it.

**Comment by zWolfrost** [comment]
Also note that to use the extension (if someone wants to test it) you have to set "dom.events.asyncClipboard.clipboardItem" to true in "about:config" (as written in its description)

**Comment by Godiesc** [comment]
hi, thanks for the report, is an interesting add-on, the lines you mentioned are for the background-color of the about: pages, it seems like that extension in some way use that url or something like that, rare. I will tested and see if a solution is possible.

**Comment by zWolfrost** [comment]
Hi, thank you for your time. As i said above, you don't need to do a lot to replicate this behavior. You just need to install the add-on and set "dom.events.asyncClipboard.clipboardItem" to true in "about:config" (to make it work at all, as the add-on specifies in its description). Then, just copy an image and try to upload it by pressing whatever image upload button, like google reverse image search or imgur. I will add a screenshot of how it's **supposed** to be instead (i removed the previously stated lines).

![image](https://github.com/Godiesc/firefox-gx/assets/101343066/85390c2c-30a2-4d73-a7ff-97dd5c38a981)

**Comment by Godiesc** [comment]
the extension is rare, we can upload the image with Ctrl + v, or maybe is for sites that can't do that. I updated the file [ogx_UC-settings-addons-pages.css](https://github.com/Godiesc/firefox-gx/blob/main/chrome/components/ogx_UC-settings-addons-pages.css), you can test to see if all works fine now.

**Comment by Godiesc** [comment]
@zWolfrost I updated the file [ogx_UC-settings-addons-pages.css](https://github.com/Godiesc/firefox-gx/blob/main/chrome/components/ogx_UC-settings-addons-pages.css) to solve the problem, thanks for your report.

**Comment by zWolfrost** [comment]
Thank you very much for fixing the background, however i also asked to replace in some way lines "561" and "568" from "ogx_UC-newtabpage.css" because they make the extension background white for some reason. Is that normal behavior?

![image](https://github.com/Godiesc/firefox-gx/assets/101343066/fd38227b-ed85-4831-8867-42bb639c3c24)

**Comment by Godiesc** [comment]
hi again, I made a little change to the `ogx_UC-newtabpage.css` file to solve that, thanks for the report. 💙
