### ISSUE TITLE
Bug in latest v119 beta

### ISSUE THREAD

**Issue by GrPK** [Godiesc/firefox-gx#84]
Hello, as you said in your latest release regarding bugs on beta version, here's a bug with tabs 
![image](https://github.com/Godiesc/firefox-gx/assets/31523635/6952a204-0755-47c8-b5dd-4e053030e65b)

Let me know what logs you need. Thanks in advance!

**Comment by Godiesc** [comment]
thanks for the report, I updated `ogx_contextual-menu.css`, `ogx_tabs-bar.css` and `ogx_tab-shapes.css` to solve some problems, if you want to test it.

**Comment by GrPK** [comment]
![image](https://github.com/Godiesc/firefox-gx/assets/31523635/fcd84c84-f78f-4c06-861b-02997ebd5ddd)


Bug Fixed, thanks!
