### ISSUE TITLE
Menu text persisting where it shouldn't. v.118

### ISSUE THREAD

**Issue by Big-mac23** [Godiesc/firefox-gx#85]
Hello, I am a new user who really loves the work put into this. Recently I downloaded and loaded v.118 due to some issues in the previous version. I found this Menu text persisting on opening and it does not go away. I have tried reinstalling the files, restarting my laptop and browser multiple times. I have not yet tried to uninstall the browser as I have just migrated my data. Attached below are some screenshots.

![image](https://github.com/Godiesc/firefox-gx/assets/146560171/36e59c95-2730-47ef-9058-e1a01b1ceed9)

![image](https://github.com/Godiesc/firefox-gx/assets/146560171/9dca716b-4a17-4b68-8df5-24156ab37a91) (when I open the firefox menu)

![image](https://github.com/Godiesc/firefox-gx/assets/146560171/7ae9612d-b41e-47ea-a28e-4902df6daeac)

**Comment by Godiesc** [comment]
hi, sadly I can't replicate your issue.
https://screenrec.com/share/fPYiFjEmpM

**Comment by Big-mac23** [comment]
Ok, I guess I'll reinstall my browser and then check if that fixes the
issue.

**Comment by Argonius-Angelus** [comment]
Howdy. I know this issue is marked as closed, but I also had this issue. I managed to fix it by uninstalling and re-installing the Left Sidebar extra, making sure to close and re-open firefox after uninstalling and reinstalling.
