### ISSUE TITLE
highlight color on new tab not showing

### ISSUE THREAD

**Issue by carepollo** [Godiesc/firefox-gx#87]
I am using poison color theme and yet the new tab page doesn't seem like the preview, what am I missing?
![image](https://github.com/Godiesc/firefox-gx/assets/67649525/cc3b7ebc-7c6e-4969-8476-ef76ad16732c)
![image](https://github.com/Godiesc/firefox-gx/assets/67649525/09833888-5ecc-4f01-82de-2c36f8efb521)

**Comment by Godiesc** [comment]
hi, that can't be do it automatically, you should change the wallpaper and the accent color manually for pages like newtab-page, addons page... in rhe readme of the theme you have the info to do that:

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/2d8caf92-20c3-49f2-9012-232bc999c2ba)

**Comment by carepollo** [comment]
yeah, that is what I was missing, thanks for the quick response.
