### ISSUE TITLE
Menu button does not appear on left sidebar, drawn over a tab instead

### ISSUE THREAD

**Issue by PIzza51225** [Godiesc/firefox-gx#88]
I have been trying to get the left sidebar extra to work, but every time I try to use it, the Firefox logo used to open the menu does not get placed on the sidebar like it should. Instead, it stayed in its original spot in vanilla Firefox, being drawn another tab instead. I have tried everything to fix this, even editing the Menu button in the CSS. I have been unable to fix this issue. This is slightly annoying since I have seen this work as it should in the previews. Can anyone please help me with this?

![image](https://github.com/Godiesc/firefox-gx/assets/29574356/ba1f26f2-0d68-4919-8f72-a0c9c4024993)

**Comment by Godiesc** [comment]
hi, if you are using beta, developer or nightly version of Firefox could appear some issues, you should download the theme form the [release section](https://github.com/Godiesc/firefox-gx/releases) and use Firefox release version, if you using Firefox v118 and using the theme 118 version you shouldn't have any problem.

**Comment by PIzza51225** [comment]
I am using the latest version of Firefox GX and am on Firefox version 118.0.2. Problem persists.
![image](https://github.com/Godiesc/firefox-gx/assets/29574356/0a48ae59-5596-4307-bf60-12ec40a9073a)
![image](https://github.com/Godiesc/firefox-gx/assets/29574356/da8e338a-99b4-4588-bd98-15ceb71ebf6b)

**Comment by Godiesc** [comment]
I just tested in a new profile and works fine, be sure to replace the ogx_left-sidebar.css, sometimes the people just update the default files inside components folder and not the "Extra" files.

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/65f43976-c555-4235-8a8e-d396d058b168)

**Comment by PIzza51225** [comment]
How do I do that? This is my first time doing anything like this.

**Comment by PIzza51225** [comment]
Also, I am using the latest version of the left sidebar released 2 weeks ago.

**Comment by Godiesc** [comment]
in the file you downloaded (FirefoxGX_Release_v.118.zip ) there is a folder named "Extras", inside that you have the left-sidebar folder and the files you need to paste in chrome/components folder, it seems you are using the beta code (updated 2 weeks ago) of the left-sidebar and for that you see that problems.

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/b1d39552-f847-4396-ae5b-168b500ce724)

in 5 days will arrive the next release of firefox (119) and the theme will have a new way to active the extra features, a easiest way, stay in touch :)

**Comment by PIzza51225** [comment]
Okay, yep, it was the newest version that was causing the problems. I moved the latest version into the Components folder, and now the button is placed in the correct area.

Thank you =)
![image](https://github.com/Godiesc/firefox-gx/assets/29574356/c87861cb-c595-436d-91e8-06c45553e371)

**Comment by Godiesc** [comment]
glad to see all good. :) 👍
