### ISSUE TITLE
left sidebar

### ISSUE THREAD

**Issue by AZ790** [Godiesc/firefox-gx#90]
while trying to install the left sidebar i followed all the instructions but it still doesn't work.

system:macos ventura 13.6

**Comment by Godiesc** [comment]
Hi, the information was updated for the upcoming version of the theme, sorry for the inconveniences, for apply the left-sidebar you should paste the ogx_left-sidebar.css (from extras folder) into chrome/components folder. Let me know if works.

**Comment by AZ790** [comment]
> Hi, the information was updated for the upcoming version of the theme, sorry for the inconveniences, for apply the left-sidebar you should paste the ogx_left-sidebar.css (from extras folder) into chrome/components folder. Let me know if works.

thank you so much

**Comment by Godiesc** [comment]
I recommend you update the theme with the latest version, the steps you did first, will work now.
