### ISSUE TITLE
Strange shape new tabs

### ISSUE THREAD

**Issue by Crissu23** [Godiesc/firefox-gx#92]
![image](https://github.com/Godiesc/firefox-gx/assets/148685757/892e4cfc-4b1d-4e6e-a7cd-87737facb983)

As title said. Latest Firefox, stable, 119, clean install

**Comment by Godiesc** [comment]
hi, you mean you updated the browser to v.119 and updated the theme with the version 119 and that bug happened? I tested the theme before the release and didn't see problems. I'll take a look if you confirm me that you updated the theme also.

**Comment by Crissu23** [comment]
I uptaded the browser to v119, then I saw the bug. I deleted chrome/user.js, reinstalled theme using latest zip from Releases but the bug is still here

**Comment by Godiesc** [comment]
I just tested and looks good, for this release of the theme the "Extra" features are activate in about:config page,read the corresponding section to know how.

![preview](https://github.com/Godiesc/firefox-gx/assets/22057609/fdaa6009-654e-4477-94d8-01164183031a)
