### ISSUE TITLE
Tab Shapes Are Ignored (Nightly 121.0a1 - 2023-10-25)

### ISSUE THREAD

**Issue by Ceru6479** [Godiesc/firefox-gx#93]
![Screenshot_160](https://github.com/Godiesc/firefox-gx/assets/116467020/66ed86dc-5364-4118-85a0-5f054e04983b)

![Screenshot_161](https://github.com/Godiesc/firefox-gx/assets/116467020/423c883d-5b98-4cb8-9b67-0457d4ebb636)

![Screenshot_162](https://github.com/Godiesc/firefox-gx/assets/116467020/16940f73-8a00-472a-845f-3715d8cc90a5)

![Screenshot_163](https://github.com/Godiesc/firefox-gx/assets/116467020/8483f386-eccc-4292-bc79-d84c2b4fe19a)

The "Tab Shapes" setting is ignored when it shouldn't. I reinstalled with the latest release version (for V119) and set the tab-shapes config to True but the issue remains.

**Comment by Godiesc** [comment]
thanks for the report, Firefox updated the way that use the preferences in css so, none of the preferences of the theme will work, I will fix the theme tomorrow when I woke up, right now I'm putting my pijama for sleep. 😴🛌

**Comment by Godiesc** [comment]
solved with the latest update of the files, you should download from `code -> download zip` , now you can see the changes made in about:config page instantly without restart the browser.

**Comment by Ceru6479** [comment]
The issue has been resolved. Thanks!
