### ISSUE TITLE
Some menus will open outside the window to the left sometimes.

### ISSUE THREAD

**Issue by matt1432** [Godiesc/firefox-gx#94]
Thank you for the beautiful theme! I've always loved Opera GX's UI but the chinese spyware is a bit of a deal-breaker for me, so thank you for bringing this to Firefox.

However, when the firefox window isn't taking up the entire monitor, the main menu opens to the left (see picture). 

This also happens when installing an addon, where it always shows up to the left and doesn't allow me to enable the addon in private tabs.

![image](https://github.com/Godiesc/firefox-gx/assets/98562002/16efca0e-f601-4cce-8e8c-dcf3323007d6)

**Comment by Godiesc** [comment]
hi,
for default the redesigned menu will appear only with maximized window, in normal window will appear the default form, like this: 

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/78f49017-85e1-4b34-b344-96ff53cd8f46)

you can add extra info like your OS, version of Firefox, version of the theme, extra features activated, or maybe your OS simulate maximized windows when it doesn't? who knows.

**Comment by matt1432** [comment]
I have had this issue on 2 machines

Additional info:
OS : Linux NixOS and Archlinux
WM/DE: Hyprland or KDE
Firefox 119 with version 8.5 of this theme
Firefox 118 with version 8.4 of this theme

I have tab shapes and left sidebar on

**Comment by matt1432** [comment]
Is there a way to always force the default form? That could help with my issue

**Comment by Godiesc** [comment]
in your screenshot I see you have other window in the left side, so its the feature of the OS for put different windows on the sides, linux allows you to have up to 4 windows in the corners of the screen, are you using that, I guess, maybe that the browser interprets like maximized, don't happens in windows-10. I will test in manjaro-kde if the problem is that, maybe could search for a solution.

> Is there a way to always force the default form? That could help with my issue

maybe deleting some parts of the code of `ogx_menu.css` (code of the label and code blocks when "maximized" exist) and `ogx_left-sidebar.css` in the section of -Nuevos margenes Botón menú- when "maximized" exist", being careful with brackets "{ }".

I made a fast edit to do that:
ogx_menu.css : https://pastebin.com/B60xnRcn
ogx_left-sidebar.css : https://pastebin.com/yFvwfdwt

**Comment by matt1432** [comment]
That's great! Fixes my issue of it not being pretty, thank you. However my other issue was that since it puts the menu outside the window, there are some menus I can't access. For example:

![image](https://github.com/Godiesc/firefox-gx/assets/98562002/01092438-f935-4a17-956b-a5da6387aed3)

![image](https://github.com/Godiesc/firefox-gx/assets/98562002/892945b9-4c77-4445-93aa-9050ced9732d)

**Comment by Godiesc** [comment]
![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/f878fef8-2cfb-4cfc-ad35-f531b7ca9ea7)

that is a OS problem, or your config of your mouse "focus", I can't do anything for that.

**Comment by matt1432** [comment]
Since I really want the extension button on the left I tried something and wanted your opinion on if it was a good idea or not:

![image](https://github.com/Godiesc/firefox-gx/assets/98562002/e2312ba1-5cbc-4232-a24b-97e565ce4bd7)

![image](https://github.com/Godiesc/firefox-gx/assets/98562002/7a6690c9-6986-45e4-946e-bd00734268f4)

By setting this margin-inline to -505px it works. I don't know if that would break anything else though

**Comment by Godiesc** [comment]
you can see what panels are you affecting with that, but if you don't see a problem so all is good, you solved. :) 

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/081db536-e167-4bd2-8df7-582b023ccc44)

**Comment by matt1432** [comment]
This is what I've added to my custom css file to fix my issues:
```css
#notification-popup {
  margin-top: -1px !important;
  margin-inline: -505px !important;
}

#customizationui-widget-panel {
  margin-top: -1px !important;
  margin-inline: -200px !important;
}
```

Thank your for you help with all my issues!
