### ISSUE TITLE
Left side-bar displays as a blank gray, and no bookmark whatsoever.

### ISSUE THREAD

**Issue by Akurio64** [Godiesc/firefox-gx#95]
Despite the fact I uninstalled the old version, installed the new version, and added the variables in the about:config. What am I missing?
![image](https://github.com/Godiesc/firefox-gx/assets/89168744/bb8a456c-aabb-4464-bec8-c513fb4c3416)

**Comment by Godiesc** [comment]
hi, you should have the bookmarks-bar in "always show"

![Sin título](https://github.com/Godiesc/firefox-gx/assets/22057609/d89c0d05-13c2-4262-a4f8-297c2ce28889)

**Comment by Akurio64** [comment]
Thanks, I didn't know what that meant. I thought it was just another value to add in about:config
