### ISSUE TITLE
Tab Weird Shapes in 119

### ISSUE THREAD

**Issue by iErod** [Godiesc/firefox-gx#96]
![Screenshot 2023-10-31 170310](https://github.com/Godiesc/firefox-gx/assets/149528792/1689d5f5-9418-48ec-a275-133d4a6eb93c)

![Screenshot 2023-10-31 170345](https://github.com/Godiesc/firefox-gx/assets/149528792/cd820041-9876-4291-8e1a-90786cb73df8)

![Screenshot 2023-10-31 170406](https://github.com/Godiesc/firefox-gx/assets/149528792/14695fc5-9f2c-40a7-84e3-f8baae2a9744)

I have reinstalled and followed the instructions in both pages. I have firefox color on.

**Comment by Godiesc** [comment]
hi, I don't know about "firefox-color" compatibility, but if you installed the theme from "Releases" section and follow the new "Steps to apply" and you use Firefox v.119, you wouldn't see any problem.

**Comment by iErod** [comment]
Even disabling firefox color will have the same issue. I installed v119 from the releases and followed those steps. I even deleted the chrome folder and fresh installed all of the files from there.

**Comment by Godiesc** [comment]
are you sure you create the preference in about:config page?

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/1d7e02ac-5399-40e8-a612-c5d77e250dca)

**Comment by iErod** [comment]
Yes. These are all the configs I have set up.

![image](https://github.com/Godiesc/firefox-gx/assets/149528792/3325f44f-87e7-4047-b328-eb182e2d3f36)

This is what my user.js file looks like.
![image](https://github.com/Godiesc/firefox-gx/assets/149528792/b8eb16e8-696e-454b-bc51-a306d6143af6)

**Comment by Godiesc** [comment]
I just tested again and looks good. Be sure Firefox-color is disabled and choose a compatible theme after restart the browser. Works fine with solid themes and themes with images:

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/3ad8f4b6-6658-4761-862b-5a50af7d5792)

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/4d55db91-3bd8-43e1-bf1a-24729887e80b)

**Comment by iErod** [comment]
Retried without firefox color and it looks like this now. I'm sure I just have a setting wrong somewhere in the css files but unsure where to look.

![image](https://github.com/Godiesc/firefox-gx/assets/149528792/c3ddbc0b-830a-43d9-9088-76625202181c)

**Comment by Godiesc** [comment]
with v.119 of the theme you don't have to paste any file into components folder, all the files are there. if you copy the `chrome` folder and add the preference in about:config that should be enough to do.

**Comment by iErod** [comment]
I thought so. It changes when I change the general color in "ogx_root-personal.css", so I wanted to make sure it wasn't a setting in that file.
