### ISSUE TITLE
config toggle not working

### ISSUE THREAD

**Issue by MAFiA303** [Godiesc/firefox-gx#97]
loving the new updates, good job as always.
I updated the code to the recent version and it is not working,
steps:

- about:config
- firefoxgx.tree-tabs --> true
- firefoxgx.left-sidebar --> true

this are not taking effect, im on windows 11

**Comment by Godiesc** [comment]
hi,
for firefox v.119 you should download from the "Releases" section, if you use beta use: `code -> download zip`

**Comment by MAFiA303** [comment]
> hi, for firefox v.119 you should download from the "Releases" section, if you use beta use: `code -> download zip`

i am using FF version 120.0b5 (64-bit)
i added files using `clone` initially, and now downloaded with `code -> download.zip`

the tabs are both in the left tree and on the top.
also this is back [header for side nav]
![image](https://github.com/Godiesc/firefox-gx/assets/3491396/25576ba2-5cdc-44a6-8ee5-8f2a688b3d26)

**Comment by Godiesc** [comment]
maybe you are using too the preference for oneline config, that is not compatible, be sure to not have it.

**Comment by MAFiA303** [comment]
I just toggled it off, and still tabs are showing on top.
I am using sideberry

**Comment by Godiesc** [comment]
I updated the files just now, thanks for the report, the problem is solve. 
If you see ither bugs pls report, I can't test all the styles all the time with every change.
💙

**Comment by MAFiA303** [comment]
great job as always. its working amazingly
