### ISSUE TITLE
Missing border under tabs in Nightly

### ISSUE THREAD

**Issue by 253ping** [Godiesc/firefox-gx#99]
When using Themes like Fuchsia (, Blue, ...) the border under the tabs are missing.

In Firefox Nightly 121.0a1 (2023-11-03) the border between tabs and search bar is missing.
![image](https://github.com/Godiesc/firefox-gx/assets/66729859/6ee5f43d-87a5-412b-9962-2260b15c3035)

In Firefox Developer Edition 120.0b6 it appears like it's intended.
![image](https://github.com/Godiesc/firefox-gx/assets/66729859/935720d8-8bdb-4ab4-9aa1-b5a8ef25e50b)

When using Themes which do set an background (Purple Sky, Red Blur, ...) it works in both versions.
![image](https://github.com/Godiesc/firefox-gx/assets/66729859/84f097e5-d82a-4244-942c-a549bdbb256a)
![image](https://github.com/Godiesc/firefox-gx/assets/66729859/7e5fcd1a-dec8-4161-9d59-0cdcfd75a57f)

**Comment by Godiesc** [comment]
Thanks for the report, when arrive to beta version I'll fix it, if I try to fix now maybe that change don't appears in v.120 and will cause issues.

**Comment by Godiesc** [comment]
@253ping I fixed that just right now.
additionally Firefox seems to update the way themes with images works, the image don't align with the selected tab, so maybe that is something unsolvable, sadly.
